/* Generated by Yosys 0.44+20 (git sha1 5fb3c0b1d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "cajero.v:1.1-163.10" *)
module cajero(clk, rst, TARJETA_RECIBIDA, TIPO_TRNANS, DIGITO, DIGITO_STB, PIN, MONTO, MONTO_STB, BALANCE_INICIAL, BALANCE_ACTUALIZADO, ENTREGAR_DINERO, PIN_INCORRECTO, ADVERTENCIA, BLOQUEO, FONDOS_INSUFICIENTES);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  (* force_downto = 32'd1 *)
  (* src = "cajero.v:0.0-0.0|cajero.v:57.9-160.16|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [2:0] _0642_;
  (* src = "cajero.v:6.49-6.60" *)
  output ADVERTENCIA;
  wire ADVERTENCIA;
  (* src = "cajero.v:6.93-6.112" *)
  output BALANCE_ACTUALIZADO;
  wire BALANCE_ACTUALIZADO;
  (* src = "cajero.v:10.23-10.38" *)
  input [63:0] BALANCE_INICIAL;
  wire [63:0] BALANCE_INICIAL;
  (* src = "cajero.v:6.62-6.69" *)
  output BLOQUEO;
  wire BLOQUEO;
  (* src = "cajero.v:7.22-7.28" *)
  input [3:0] DIGITO;
  wire [3:0] DIGITO;
  (* src = "cajero.v:5.53-5.63" *)
  input DIGITO_STB;
  wire DIGITO_STB;
  (* src = "cajero.v:6.16-6.31" *)
  output ENTREGAR_DINERO;
  wire ENTREGAR_DINERO;
  (* src = "cajero.v:14.15-14.26" *)
  wire [2:0] EstPresente;
  (* src = "cajero.v:6.71-6.91" *)
  output FONDOS_INSUFICIENTES;
  wire FONDOS_INSUFICIENTES;
  (* src = "cajero.v:9.23-9.28" *)
  input [31:0] MONTO;
  wire [31:0] MONTO;
  (* src = "cajero.v:5.65-5.74" *)
  input MONTO_STB;
  wire MONTO_STB;
  (* src = "cajero.v:8.23-8.26" *)
  input [15:0] PIN;
  wire [15:0] PIN;
  (* src = "cajero.v:6.33-6.47" *)
  output PIN_INCORRECTO;
  wire PIN_INCORRECTO;
  (* src = "cajero.v:14.28-14.38" *)
  reg [2:0] ProxEstado;
  (* src = "cajero.v:5.22-5.38" *)
  input TARJETA_RECIBIDA;
  wire TARJETA_RECIBIDA;
  (* src = "cajero.v:5.40-5.51" *)
  input TIPO_TRNANS;
  wire TIPO_TRNANS;
  (* src = "cajero.v:5.12-5.15" *)
  input clk;
  wire clk;
  (* src = "cajero.v:12.15-12.32" *)
  wire [1:0] contador_intentos;
  (* src = "cajero.v:13.16-13.28" *)
  wire [15:0] pin_recibido;
  (* src = "cajero.v:5.17-5.20" *)
  input rst;
  wire rst;
  NOT _0643_ (
    .A(contador_intentos[0]),
    .Y(_0022_)
  );
  NOT _0644_ (
    .A(rst),
    .Y(_0023_)
  );
  NOT _0645_ (
    .A(pin_recibido[2]),
    .Y(_0024_)
  );
  NOT _0646_ (
    .A(pin_recibido[5]),
    .Y(_0025_)
  );
  NOT _0647_ (
    .A(pin_recibido[7]),
    .Y(_0026_)
  );
  NOT _0648_ (
    .A(pin_recibido[9]),
    .Y(_0027_)
  );
  NOT _0649_ (
    .A(EstPresente[2]),
    .Y(_0028_)
  );
  NOT _0650_ (
    .A(EstPresente[0]),
    .Y(_0029_)
  );
  NOT _0651_ (
    .A(EstPresente[1]),
    .Y(_0030_)
  );
  NOT _0652_ (
    .A(DIGITO_STB),
    .Y(_0031_)
  );
  NOT _0653_ (
    .A(MONTO[1]),
    .Y(_0032_)
  );
  NOT _0654_ (
    .A(MONTO[2]),
    .Y(_0033_)
  );
  NOT _0655_ (
    .A(MONTO[3]),
    .Y(_0034_)
  );
  NOT _0656_ (
    .A(MONTO[4]),
    .Y(_0035_)
  );
  NOT _0657_ (
    .A(MONTO[5]),
    .Y(_0036_)
  );
  NOT _0658_ (
    .A(MONTO[6]),
    .Y(_0037_)
  );
  NOT _0659_ (
    .A(MONTO[7]),
    .Y(_0038_)
  );
  NOT _0660_ (
    .A(MONTO[8]),
    .Y(_0039_)
  );
  NOT _0661_ (
    .A(MONTO[9]),
    .Y(_0040_)
  );
  NOT _0662_ (
    .A(MONTO[10]),
    .Y(_0041_)
  );
  NOT _0663_ (
    .A(MONTO[11]),
    .Y(_0042_)
  );
  NOT _0664_ (
    .A(MONTO[12]),
    .Y(_0043_)
  );
  NOT _0665_ (
    .A(MONTO[13]),
    .Y(_0044_)
  );
  NOT _0666_ (
    .A(MONTO[14]),
    .Y(_0045_)
  );
  NOT _0667_ (
    .A(MONTO[15]),
    .Y(_0046_)
  );
  NOT _0668_ (
    .A(MONTO[16]),
    .Y(_0047_)
  );
  NOT _0669_ (
    .A(MONTO[17]),
    .Y(_0048_)
  );
  NOT _0670_ (
    .A(MONTO[18]),
    .Y(_0049_)
  );
  NOT _0671_ (
    .A(MONTO[19]),
    .Y(_0050_)
  );
  NOT _0672_ (
    .A(MONTO[22]),
    .Y(_0051_)
  );
  NOT _0673_ (
    .A(MONTO[23]),
    .Y(_0052_)
  );
  NOT _0674_ (
    .A(MONTO[24]),
    .Y(_0053_)
  );
  NOT _0675_ (
    .A(MONTO[25]),
    .Y(_0054_)
  );
  NOT _0676_ (
    .A(MONTO[26]),
    .Y(_0055_)
  );
  NOT _0677_ (
    .A(MONTO[27]),
    .Y(_0056_)
  );
  NOT _0678_ (
    .A(MONTO[28]),
    .Y(_0057_)
  );
  NOT _0679_ (
    .A(MONTO[29]),
    .Y(_0058_)
  );
  NOT _0680_ (
    .A(MONTO[30]),
    .Y(_0059_)
  );
  NOT _0681_ (
    .A(MONTO[31]),
    .Y(_0060_)
  );
  NOT _0682_ (
    .A(MONTO_STB),
    .Y(_0061_)
  );
  NOT _0683_ (
    .A(BALANCE_INICIAL[0]),
    .Y(_0062_)
  );
  NOT _0684_ (
    .A(BALANCE_INICIAL[1]),
    .Y(_0063_)
  );
  NOT _0685_ (
    .A(BALANCE_INICIAL[2]),
    .Y(_0064_)
  );
  NOT _0686_ (
    .A(BALANCE_INICIAL[3]),
    .Y(_0065_)
  );
  NOT _0687_ (
    .A(BALANCE_INICIAL[4]),
    .Y(_0066_)
  );
  NOT _0688_ (
    .A(BALANCE_INICIAL[5]),
    .Y(_0067_)
  );
  NOT _0689_ (
    .A(BALANCE_INICIAL[6]),
    .Y(_0068_)
  );
  NOT _0690_ (
    .A(BALANCE_INICIAL[7]),
    .Y(_0069_)
  );
  NOT _0691_ (
    .A(BALANCE_INICIAL[8]),
    .Y(_0070_)
  );
  NOT _0692_ (
    .A(BALANCE_INICIAL[9]),
    .Y(_0071_)
  );
  NOT _0693_ (
    .A(BALANCE_INICIAL[10]),
    .Y(_0072_)
  );
  NOT _0694_ (
    .A(BALANCE_INICIAL[11]),
    .Y(_0073_)
  );
  NOT _0695_ (
    .A(BALANCE_INICIAL[12]),
    .Y(_0074_)
  );
  NOT _0696_ (
    .A(BALANCE_INICIAL[13]),
    .Y(_0075_)
  );
  NOT _0697_ (
    .A(BALANCE_INICIAL[14]),
    .Y(_0076_)
  );
  NOT _0698_ (
    .A(BALANCE_INICIAL[15]),
    .Y(_0077_)
  );
  NOT _0699_ (
    .A(BALANCE_INICIAL[16]),
    .Y(_0078_)
  );
  NOT _0700_ (
    .A(BALANCE_INICIAL[17]),
    .Y(_0079_)
  );
  NOT _0701_ (
    .A(BALANCE_INICIAL[18]),
    .Y(_0080_)
  );
  NOT _0702_ (
    .A(BALANCE_INICIAL[19]),
    .Y(_0081_)
  );
  NOT _0703_ (
    .A(BALANCE_INICIAL[20]),
    .Y(_0082_)
  );
  NOT _0704_ (
    .A(BALANCE_INICIAL[21]),
    .Y(_0083_)
  );
  NOT _0705_ (
    .A(BALANCE_INICIAL[22]),
    .Y(_0084_)
  );
  NOT _0706_ (
    .A(BALANCE_INICIAL[23]),
    .Y(_0085_)
  );
  NOT _0707_ (
    .A(BALANCE_INICIAL[24]),
    .Y(_0086_)
  );
  NOT _0708_ (
    .A(BALANCE_INICIAL[25]),
    .Y(_0087_)
  );
  NOT _0709_ (
    .A(BALANCE_INICIAL[26]),
    .Y(_0088_)
  );
  NOT _0710_ (
    .A(BALANCE_INICIAL[27]),
    .Y(_0089_)
  );
  NOT _0711_ (
    .A(BALANCE_INICIAL[28]),
    .Y(_0090_)
  );
  NOT _0712_ (
    .A(BALANCE_INICIAL[29]),
    .Y(_0091_)
  );
  NOT _0713_ (
    .A(BALANCE_INICIAL[30]),
    .Y(_0092_)
  );
  NOT _0714_ (
    .A(BALANCE_INICIAL[31]),
    .Y(_0093_)
  );
  NOT _0715_ (
    .A(PIN[2]),
    .Y(_0094_)
  );
  NOT _0716_ (
    .A(PIN[5]),
    .Y(_0095_)
  );
  NOT _0717_ (
    .A(PIN[7]),
    .Y(_0096_)
  );
  NOT _0718_ (
    .A(PIN[9]),
    .Y(_0097_)
  );
  NOT _0719_ (
    .A(pin_recibido[12]),
    .Y(_0098_)
  );
  NOT _0720_ (
    .A(PIN[12]),
    .Y(_0099_)
  );
  NOT _0721_ (
    .A(pin_recibido[15]),
    .Y(_0100_)
  );
  NOT _0722_ (
    .A(PIN[15]),
    .Y(_0101_)
  );
  NAND _0723_ (
    .A(DIGITO[0]),
    .B(rst),
    .Y(_0102_)
  );
  NOT _0724_ (
    .A(_0102_),
    .Y(_0001_)
  );
  NAND _0725_ (
    .A(rst),
    .B(DIGITO[1]),
    .Y(_0103_)
  );
  NOT _0726_ (
    .A(_0103_),
    .Y(_0002_)
  );
  NAND _0727_ (
    .A(rst),
    .B(DIGITO[2]),
    .Y(_0104_)
  );
  NOT _0728_ (
    .A(_0104_),
    .Y(_0003_)
  );
  NAND _0729_ (
    .A(rst),
    .B(DIGITO[3]),
    .Y(_0105_)
  );
  NOT _0730_ (
    .A(_0105_),
    .Y(_0004_)
  );
  NAND _0731_ (
    .A(rst),
    .B(pin_recibido[0]),
    .Y(_0106_)
  );
  NOT _0732_ (
    .A(_0106_),
    .Y(_0005_)
  );
  NAND _0733_ (
    .A(rst),
    .B(pin_recibido[1]),
    .Y(_0107_)
  );
  NOT _0734_ (
    .A(_0107_),
    .Y(_0006_)
  );
  NAND _0735_ (
    .A(rst),
    .B(pin_recibido[2]),
    .Y(_0108_)
  );
  NOT _0736_ (
    .A(_0108_),
    .Y(_0007_)
  );
  NAND _0737_ (
    .A(rst),
    .B(pin_recibido[3]),
    .Y(_0109_)
  );
  NOT _0738_ (
    .A(_0109_),
    .Y(_0008_)
  );
  NAND _0739_ (
    .A(rst),
    .B(pin_recibido[4]),
    .Y(_0110_)
  );
  NOT _0740_ (
    .A(_0110_),
    .Y(_0009_)
  );
  NAND _0741_ (
    .A(rst),
    .B(pin_recibido[5]),
    .Y(_0111_)
  );
  NOT _0742_ (
    .A(_0111_),
    .Y(_0010_)
  );
  NAND _0743_ (
    .A(rst),
    .B(pin_recibido[6]),
    .Y(_0112_)
  );
  NOT _0744_ (
    .A(_0112_),
    .Y(_0011_)
  );
  NAND _0745_ (
    .A(rst),
    .B(pin_recibido[7]),
    .Y(_0113_)
  );
  NOT _0746_ (
    .A(_0113_),
    .Y(_0012_)
  );
  NAND _0747_ (
    .A(rst),
    .B(pin_recibido[8]),
    .Y(_0114_)
  );
  NOT _0748_ (
    .A(_0114_),
    .Y(_0013_)
  );
  NAND _0749_ (
    .A(rst),
    .B(pin_recibido[9]),
    .Y(_0115_)
  );
  NOT _0750_ (
    .A(_0115_),
    .Y(_0014_)
  );
  NAND _0751_ (
    .A(rst),
    .B(pin_recibido[10]),
    .Y(_0116_)
  );
  NOT _0752_ (
    .A(_0116_),
    .Y(_0015_)
  );
  NAND _0753_ (
    .A(rst),
    .B(pin_recibido[11]),
    .Y(_0117_)
  );
  NOT _0754_ (
    .A(_0117_),
    .Y(_0016_)
  );
  NAND _0755_ (
    .A(rst),
    .B(ProxEstado[0]),
    .Y(_0118_)
  );
  NOT _0756_ (
    .A(_0118_),
    .Y(_0017_)
  );
  NAND _0757_ (
    .A(rst),
    .B(ProxEstado[1]),
    .Y(_0119_)
  );
  NOT _0758_ (
    .A(_0119_),
    .Y(_0018_)
  );
  NAND _0759_ (
    .A(rst),
    .B(ProxEstado[2]),
    .Y(_0120_)
  );
  NOT _0760_ (
    .A(_0120_),
    .Y(_0019_)
  );
  NAND _0761_ (
    .A(pin_recibido[15]),
    .B(_0101_),
    .Y(_0121_)
  );
  NAND _0762_ (
    .A(_0100_),
    .B(PIN[15]),
    .Y(_0122_)
  );
  NAND _0763_ (
    .A(_0121_),
    .B(_0122_),
    .Y(_0123_)
  );
  NAND _0764_ (
    .A(_0027_),
    .B(PIN[9]),
    .Y(_0124_)
  );
  NOR _0765_ (
    .A(_0025_),
    .B(PIN[5]),
    .Y(_0125_)
  );
  NAND _0766_ (
    .A(pin_recibido[12]),
    .B(_0099_),
    .Y(_0126_)
  );
  NAND _0767_ (
    .A(_0098_),
    .B(PIN[12]),
    .Y(_0127_)
  );
  NAND _0768_ (
    .A(_0126_),
    .B(_0127_),
    .Y(_0128_)
  );
  NAND _0769_ (
    .A(pin_recibido[11]),
    .B(PIN[11]),
    .Y(_0129_)
  );
  NOR _0770_ (
    .A(pin_recibido[11]),
    .B(PIN[11]),
    .Y(_0130_)
  );
  NOT _0771_ (
    .A(_0130_),
    .Y(_0131_)
  );
  NAND _0772_ (
    .A(_0129_),
    .B(_0131_),
    .Y(_0132_)
  );
  NAND _0773_ (
    .A(pin_recibido[2]),
    .B(_0094_),
    .Y(_0133_)
  );
  NAND _0774_ (
    .A(_0024_),
    .B(PIN[2]),
    .Y(_0134_)
  );
  NOR _0775_ (
    .A(pin_recibido[6]),
    .B(PIN[6]),
    .Y(_0135_)
  );
  NAND _0776_ (
    .A(pin_recibido[6]),
    .B(PIN[6]),
    .Y(_0136_)
  );
  NOT _0777_ (
    .A(_0136_),
    .Y(_0137_)
  );
  NOR _0778_ (
    .A(_0135_),
    .B(_0137_),
    .Y(_0138_)
  );
  NOR _0779_ (
    .A(pin_recibido[0]),
    .B(PIN[0]),
    .Y(_0139_)
  );
  NAND _0780_ (
    .A(pin_recibido[0]),
    .B(PIN[0]),
    .Y(_0140_)
  );
  NOT _0781_ (
    .A(_0140_),
    .Y(_0141_)
  );
  NOR _0782_ (
    .A(_0139_),
    .B(_0141_),
    .Y(_0142_)
  );
  NOR _0783_ (
    .A(pin_recibido[13]),
    .B(PIN[13]),
    .Y(_0143_)
  );
  NAND _0784_ (
    .A(pin_recibido[13]),
    .B(PIN[13]),
    .Y(_0144_)
  );
  NOT _0785_ (
    .A(_0144_),
    .Y(_0145_)
  );
  NOR _0786_ (
    .A(_0143_),
    .B(_0145_),
    .Y(_0146_)
  );
  NOR _0787_ (
    .A(pin_recibido[1]),
    .B(PIN[1]),
    .Y(_0147_)
  );
  NOT _0788_ (
    .A(_0147_),
    .Y(_0148_)
  );
  NAND _0789_ (
    .A(pin_recibido[1]),
    .B(PIN[1]),
    .Y(_0149_)
  );
  NAND _0790_ (
    .A(_0148_),
    .B(_0149_),
    .Y(_0150_)
  );
  NAND _0791_ (
    .A(_0026_),
    .B(PIN[7]),
    .Y(_0151_)
  );
  NOR _0792_ (
    .A(pin_recibido[5]),
    .B(_0095_),
    .Y(_0152_)
  );
  NAND _0793_ (
    .A(pin_recibido[7]),
    .B(_0096_),
    .Y(_0153_)
  );
  NAND _0794_ (
    .A(pin_recibido[9]),
    .B(_0097_),
    .Y(_0154_)
  );
  NAND _0795_ (
    .A(pin_recibido[8]),
    .B(PIN[8]),
    .Y(_0155_)
  );
  NOT _0796_ (
    .A(_0155_),
    .Y(_0156_)
  );
  NOR _0797_ (
    .A(pin_recibido[8]),
    .B(PIN[8]),
    .Y(_0157_)
  );
  NOR _0798_ (
    .A(_0156_),
    .B(_0157_),
    .Y(_0158_)
  );
  NAND _0799_ (
    .A(pin_recibido[4]),
    .B(PIN[4]),
    .Y(_0159_)
  );
  NOT _0800_ (
    .A(_0159_),
    .Y(_0160_)
  );
  NOR _0801_ (
    .A(pin_recibido[4]),
    .B(PIN[4]),
    .Y(_0161_)
  );
  NOR _0802_ (
    .A(_0160_),
    .B(_0161_),
    .Y(_0162_)
  );
  NOR _0803_ (
    .A(pin_recibido[14]),
    .B(PIN[14]),
    .Y(_0163_)
  );
  NOT _0804_ (
    .A(_0163_),
    .Y(_0164_)
  );
  NAND _0805_ (
    .A(pin_recibido[14]),
    .B(PIN[14]),
    .Y(_0165_)
  );
  NAND _0806_ (
    .A(_0164_),
    .B(_0165_),
    .Y(_0166_)
  );
  NOR _0807_ (
    .A(pin_recibido[10]),
    .B(PIN[10]),
    .Y(_0167_)
  );
  NAND _0808_ (
    .A(pin_recibido[10]),
    .B(PIN[10]),
    .Y(_0168_)
  );
  NOT _0809_ (
    .A(_0168_),
    .Y(_0169_)
  );
  NOR _0810_ (
    .A(_0167_),
    .B(_0169_),
    .Y(_0170_)
  );
  NAND _0811_ (
    .A(pin_recibido[3]),
    .B(PIN[3]),
    .Y(_0171_)
  );
  NOT _0812_ (
    .A(_0171_),
    .Y(_0172_)
  );
  NOR _0813_ (
    .A(pin_recibido[3]),
    .B(PIN[3]),
    .Y(_0173_)
  );
  NOR _0814_ (
    .A(_0172_),
    .B(_0173_),
    .Y(_0174_)
  );
  NOR _0815_ (
    .A(_0138_),
    .B(_0174_),
    .Y(_0175_)
  );
  NAND _0816_ (
    .A(_0151_),
    .B(_0153_),
    .Y(_0176_)
  );
  NOR _0817_ (
    .A(_0128_),
    .B(_0162_),
    .Y(_0177_)
  );
  NAND _0818_ (
    .A(_0175_),
    .B(_0177_),
    .Y(_0178_)
  );
  NOR _0819_ (
    .A(_0146_),
    .B(_0176_),
    .Y(_0179_)
  );
  NAND _0820_ (
    .A(_0166_),
    .B(_0179_),
    .Y(_0180_)
  );
  NOR _0821_ (
    .A(_0178_),
    .B(_0180_),
    .Y(_0181_)
  );
  NOR _0822_ (
    .A(_0142_),
    .B(_0170_),
    .Y(_0182_)
  );
  NAND _0823_ (
    .A(_0181_),
    .B(_0182_),
    .Y(_0183_)
  );
  NAND _0824_ (
    .A(_0133_),
    .B(_0134_),
    .Y(_0184_)
  );
  NOR _0825_ (
    .A(_0152_),
    .B(_0184_),
    .Y(_0185_)
  );
  NAND _0826_ (
    .A(_0124_),
    .B(_0154_),
    .Y(_0186_)
  );
  NOR _0827_ (
    .A(_0158_),
    .B(_0186_),
    .Y(_0187_)
  );
  NAND _0828_ (
    .A(_0185_),
    .B(_0187_),
    .Y(_0188_)
  );
  NOR _0829_ (
    .A(_0123_),
    .B(_0125_),
    .Y(_0189_)
  );
  NAND _0830_ (
    .A(_0150_),
    .B(_0189_),
    .Y(_0190_)
  );
  NOR _0831_ (
    .A(_0188_),
    .B(_0190_),
    .Y(_0191_)
  );
  NAND _0832_ (
    .A(_0132_),
    .B(_0191_),
    .Y(_0192_)
  );
  NOR _0833_ (
    .A(_0183_),
    .B(_0192_),
    .Y(_0193_)
  );
  NAND _0834_ (
    .A(DIGITO_STB),
    .B(_0193_),
    .Y(_0194_)
  );
  NOR _0835_ (
    .A(EstPresente[2]),
    .B(_0029_),
    .Y(_0195_)
  );
  NAND _0836_ (
    .A(_0028_),
    .B(EstPresente[0]),
    .Y(_0196_)
  );
  NOR _0837_ (
    .A(EstPresente[1]),
    .B(_0196_),
    .Y(_0197_)
  );
  NAND _0838_ (
    .A(_0030_),
    .B(_0195_),
    .Y(_0198_)
  );
  NAND _0839_ (
    .A(contador_intentos[1]),
    .B(contador_intentos[0]),
    .Y(_0199_)
  );
  NAND _0840_ (
    .A(_0194_),
    .B(_0197_),
    .Y(_0200_)
  );
  NOR _0841_ (
    .A(_0199_),
    .B(_0200_),
    .Y(_0201_)
  );
  NOR _0842_ (
    .A(EstPresente[0]),
    .B(EstPresente[1]),
    .Y(_0202_)
  );
  NOT _0843_ (
    .A(_0202_),
    .Y(_0203_)
  );
  NAND _0844_ (
    .A(TARJETA_RECIBIDA),
    .B(_0202_),
    .Y(_0204_)
  );
  NOR _0845_ (
    .A(EstPresente[2]),
    .B(_0204_),
    .Y(_0205_)
  );
  NOR _0846_ (
    .A(_0197_),
    .B(_0205_),
    .Y(_0206_)
  );
  NOR _0847_ (
    .A(DIGITO_STB),
    .B(_0198_),
    .Y(_0207_)
  );
  NOR _0848_ (
    .A(_0206_),
    .B(_0207_),
    .Y(_0208_)
  );
  NOT _0849_ (
    .A(_0208_),
    .Y(_0209_)
  );
  NOR _0850_ (
    .A(_0201_),
    .B(_0209_),
    .Y(_0210_)
  );
  NOT _0851_ (
    .A(_0210_),
    .Y(_0211_)
  );
  NOR _0852_ (
    .A(_0022_),
    .B(_0210_),
    .Y(_0212_)
  );
  NOR _0853_ (
    .A(_0031_),
    .B(_0193_),
    .Y(_0213_)
  );
  NAND _0854_ (
    .A(_0197_),
    .B(_0213_),
    .Y(_0214_)
  );
  NOR _0855_ (
    .A(contador_intentos[0]),
    .B(_0214_),
    .Y(_0215_)
  );
  NOR _0856_ (
    .A(_0212_),
    .B(_0215_),
    .Y(_0216_)
  );
  NOR _0857_ (
    .A(_0023_),
    .B(_0216_),
    .Y(_0020_)
  );
  NOR _0858_ (
    .A(contador_intentos[1]),
    .B(contador_intentos[0]),
    .Y(_0217_)
  );
  NAND _0859_ (
    .A(_0197_),
    .B(_0199_),
    .Y(_0218_)
  );
  NOR _0860_ (
    .A(_0217_),
    .B(_0218_),
    .Y(_0219_)
  );
  NAND _0861_ (
    .A(_0213_),
    .B(_0219_),
    .Y(_0220_)
  );
  NAND _0862_ (
    .A(contador_intentos[1]),
    .B(_0211_),
    .Y(_0221_)
  );
  NAND _0863_ (
    .A(_0220_),
    .B(_0221_),
    .Y(_0222_)
  );
  NAND _0864_ (
    .A(rst),
    .B(_0222_),
    .Y(_0223_)
  );
  NOT _0865_ (
    .A(_0223_),
    .Y(_0021_)
  );
  NOR _0866_ (
    .A(_0059_),
    .B(BALANCE_INICIAL[30]),
    .Y(_0224_)
  );
  NAND _0867_ (
    .A(MONTO[30]),
    .B(_0092_),
    .Y(_0225_)
  );
  NOR _0868_ (
    .A(_0060_),
    .B(BALANCE_INICIAL[31]),
    .Y(_0226_)
  );
  NAND _0869_ (
    .A(MONTO[31]),
    .B(_0093_),
    .Y(_0227_)
  );
  NOR _0870_ (
    .A(_0224_),
    .B(_0226_),
    .Y(_0228_)
  );
  NOR _0871_ (
    .A(MONTO[29]),
    .B(_0091_),
    .Y(_0229_)
  );
  NOR _0872_ (
    .A(MONTO[30]),
    .B(_0092_),
    .Y(_0230_)
  );
  NAND _0873_ (
    .A(_0059_),
    .B(BALANCE_INICIAL[30]),
    .Y(_0231_)
  );
  NOR _0874_ (
    .A(MONTO[31]),
    .B(_0093_),
    .Y(_0232_)
  );
  NAND _0875_ (
    .A(_0060_),
    .B(BALANCE_INICIAL[31]),
    .Y(_0233_)
  );
  NAND _0876_ (
    .A(_0231_),
    .B(_0233_),
    .Y(_0234_)
  );
  NOR _0877_ (
    .A(_0229_),
    .B(_0234_),
    .Y(_0235_)
  );
  NOR _0878_ (
    .A(_0224_),
    .B(_0232_),
    .Y(_0236_)
  );
  NOR _0879_ (
    .A(_0226_),
    .B(_0230_),
    .Y(_0237_)
  );
  NAND _0880_ (
    .A(_0236_),
    .B(_0237_),
    .Y(_0238_)
  );
  NOR _0881_ (
    .A(_0229_),
    .B(_0238_),
    .Y(_0239_)
  );
  NAND _0882_ (
    .A(_0228_),
    .B(_0235_),
    .Y(_0240_)
  );
  NOR _0883_ (
    .A(_0057_),
    .B(BALANCE_INICIAL[28]),
    .Y(_0241_)
  );
  NAND _0884_ (
    .A(MONTO[28]),
    .B(_0090_),
    .Y(_0242_)
  );
  NOR _0885_ (
    .A(_0058_),
    .B(BALANCE_INICIAL[29]),
    .Y(_0243_)
  );
  NAND _0886_ (
    .A(MONTO[29]),
    .B(_0091_),
    .Y(_0244_)
  );
  NOR _0887_ (
    .A(_0241_),
    .B(_0243_),
    .Y(_0245_)
  );
  NAND _0888_ (
    .A(_0242_),
    .B(_0244_),
    .Y(_0246_)
  );
  NOR _0889_ (
    .A(MONTO[28]),
    .B(_0090_),
    .Y(_0247_)
  );
  NOR _0890_ (
    .A(_0246_),
    .B(_0247_),
    .Y(_0248_)
  );
  NOR _0891_ (
    .A(_0229_),
    .B(_0247_),
    .Y(_0249_)
  );
  NAND _0892_ (
    .A(_0245_),
    .B(_0249_),
    .Y(_0250_)
  );
  NOR _0893_ (
    .A(_0238_),
    .B(_0250_),
    .Y(_0251_)
  );
  NAND _0894_ (
    .A(_0239_),
    .B(_0248_),
    .Y(_0252_)
  );
  NOR _0895_ (
    .A(_0055_),
    .B(BALANCE_INICIAL[26]),
    .Y(_0253_)
  );
  NOR _0896_ (
    .A(_0056_),
    .B(BALANCE_INICIAL[27]),
    .Y(_0254_)
  );
  NOR _0897_ (
    .A(_0253_),
    .B(_0254_),
    .Y(_0255_)
  );
  NOR _0898_ (
    .A(MONTO[26]),
    .B(_0088_),
    .Y(_0256_)
  );
  NOR _0899_ (
    .A(MONTO[27]),
    .B(_0089_),
    .Y(_0257_)
  );
  NOR _0900_ (
    .A(_0256_),
    .B(_0257_),
    .Y(_0258_)
  );
  NAND _0901_ (
    .A(_0255_),
    .B(_0258_),
    .Y(_0259_)
  );
  NAND _0902_ (
    .A(MONTO[24]),
    .B(_0086_),
    .Y(_0260_)
  );
  NAND _0903_ (
    .A(MONTO[25]),
    .B(_0087_),
    .Y(_0261_)
  );
  NAND _0904_ (
    .A(_0260_),
    .B(_0261_),
    .Y(_0262_)
  );
  NAND _0905_ (
    .A(_0053_),
    .B(BALANCE_INICIAL[24]),
    .Y(_0263_)
  );
  NOR _0906_ (
    .A(MONTO[25]),
    .B(_0087_),
    .Y(_0264_)
  );
  NAND _0907_ (
    .A(_0054_),
    .B(BALANCE_INICIAL[25]),
    .Y(_0265_)
  );
  NAND _0908_ (
    .A(_0261_),
    .B(_0263_),
    .Y(_0266_)
  );
  NOR _0909_ (
    .A(_0264_),
    .B(_0266_),
    .Y(_0267_)
  );
  NAND _0910_ (
    .A(_0260_),
    .B(_0267_),
    .Y(_0268_)
  );
  NOR _0911_ (
    .A(_0259_),
    .B(_0268_),
    .Y(_0269_)
  );
  NAND _0912_ (
    .A(_0260_),
    .B(_0263_),
    .Y(_0270_)
  );
  NAND _0913_ (
    .A(_0261_),
    .B(_0265_),
    .Y(_0271_)
  );
  NOR _0914_ (
    .A(_0259_),
    .B(_0271_),
    .Y(_0272_)
  );
  NAND _0915_ (
    .A(_0251_),
    .B(_0272_),
    .Y(_0273_)
  );
  NOR _0916_ (
    .A(_0270_),
    .B(_0273_),
    .Y(_0274_)
  );
  NAND _0917_ (
    .A(_0251_),
    .B(_0269_),
    .Y(_0275_)
  );
  NOR _0918_ (
    .A(MONTO[23]),
    .B(_0085_),
    .Y(_0276_)
  );
  NOR _0919_ (
    .A(_0052_),
    .B(BALANCE_INICIAL[23]),
    .Y(_0277_)
  );
  NOR _0920_ (
    .A(_0276_),
    .B(_0277_),
    .Y(_0278_)
  );
  NOR _0921_ (
    .A(MONTO[22]),
    .B(_0084_),
    .Y(_0279_)
  );
  NOR _0922_ (
    .A(_0051_),
    .B(BALANCE_INICIAL[22]),
    .Y(_0280_)
  );
  NAND _0923_ (
    .A(MONTO[22]),
    .B(_0084_),
    .Y(_0281_)
  );
  NOR _0924_ (
    .A(_0279_),
    .B(_0280_),
    .Y(_0282_)
  );
  NOR _0925_ (
    .A(MONTO[21]),
    .B(_0083_),
    .Y(_0283_)
  );
  NAND _0926_ (
    .A(_0278_),
    .B(_0282_),
    .Y(_0284_)
  );
  NOR _0927_ (
    .A(_0283_),
    .B(_0284_),
    .Y(_0285_)
  );
  NAND _0928_ (
    .A(MONTO[20]),
    .B(_0082_),
    .Y(_0286_)
  );
  NAND _0929_ (
    .A(MONTO[21]),
    .B(_0083_),
    .Y(_0287_)
  );
  NAND _0930_ (
    .A(_0286_),
    .B(_0287_),
    .Y(_0288_)
  );
  NOR _0931_ (
    .A(MONTO[20]),
    .B(_0082_),
    .Y(_0289_)
  );
  NOR _0932_ (
    .A(_0288_),
    .B(_0289_),
    .Y(_0290_)
  );
  NAND _0933_ (
    .A(_0285_),
    .B(_0290_),
    .Y(_0291_)
  );
  NOR _0934_ (
    .A(MONTO[19]),
    .B(_0081_),
    .Y(_0292_)
  );
  NAND _0935_ (
    .A(_0050_),
    .B(BALANCE_INICIAL[19]),
    .Y(_0293_)
  );
  NAND _0936_ (
    .A(MONTO[19]),
    .B(_0081_),
    .Y(_0294_)
  );
  NAND _0937_ (
    .A(_0293_),
    .B(_0294_),
    .Y(_0295_)
  );
  NAND _0938_ (
    .A(_0048_),
    .B(BALANCE_INICIAL[17]),
    .Y(_0296_)
  );
  NOR _0939_ (
    .A(MONTO[18]),
    .B(_0080_),
    .Y(_0297_)
  );
  NOR _0940_ (
    .A(_0049_),
    .B(BALANCE_INICIAL[18]),
    .Y(_0298_)
  );
  NOR _0941_ (
    .A(_0297_),
    .B(_0298_),
    .Y(_0299_)
  );
  NAND _0942_ (
    .A(_0296_),
    .B(_0299_),
    .Y(_0300_)
  );
  NAND _0943_ (
    .A(_0294_),
    .B(_0296_),
    .Y(_0301_)
  );
  NOR _0944_ (
    .A(_0292_),
    .B(_0301_),
    .Y(_0302_)
  );
  NOR _0945_ (
    .A(_0295_),
    .B(_0300_),
    .Y(_0303_)
  );
  NAND _0946_ (
    .A(_0299_),
    .B(_0302_),
    .Y(_0304_)
  );
  NOR _0947_ (
    .A(_0047_),
    .B(BALANCE_INICIAL[16]),
    .Y(_0305_)
  );
  NAND _0948_ (
    .A(MONTO[16]),
    .B(_0078_),
    .Y(_0306_)
  );
  NOR _0949_ (
    .A(_0048_),
    .B(BALANCE_INICIAL[17]),
    .Y(_0307_)
  );
  NAND _0950_ (
    .A(MONTO[17]),
    .B(_0079_),
    .Y(_0308_)
  );
  NOR _0951_ (
    .A(_0305_),
    .B(_0307_),
    .Y(_0309_)
  );
  NAND _0952_ (
    .A(_0306_),
    .B(_0308_),
    .Y(_0310_)
  );
  NOR _0953_ (
    .A(MONTO[16]),
    .B(_0078_),
    .Y(_0311_)
  );
  NOR _0954_ (
    .A(_0310_),
    .B(_0311_),
    .Y(_0312_)
  );
  NAND _0955_ (
    .A(_0303_),
    .B(_0312_),
    .Y(_0313_)
  );
  NOR _0956_ (
    .A(_0291_),
    .B(_0313_),
    .Y(_0314_)
  );
  NAND _0957_ (
    .A(_0303_),
    .B(_0309_),
    .Y(_0315_)
  );
  NOR _0958_ (
    .A(_0291_),
    .B(_0311_),
    .Y(_0316_)
  );
  NAND _0959_ (
    .A(_0274_),
    .B(_0316_),
    .Y(_0317_)
  );
  NOR _0960_ (
    .A(_0315_),
    .B(_0317_),
    .Y(_0318_)
  );
  NAND _0961_ (
    .A(_0274_),
    .B(_0314_),
    .Y(_0319_)
  );
  NOR _0962_ (
    .A(MONTO[12]),
    .B(_0074_),
    .Y(_0320_)
  );
  NAND _0963_ (
    .A(_0043_),
    .B(BALANCE_INICIAL[12]),
    .Y(_0321_)
  );
  NOR _0964_ (
    .A(MONTO[13]),
    .B(_0075_),
    .Y(_0322_)
  );
  NAND _0965_ (
    .A(_0044_),
    .B(BALANCE_INICIAL[13]),
    .Y(_0323_)
  );
  NOR _0966_ (
    .A(_0320_),
    .B(_0322_),
    .Y(_0324_)
  );
  NAND _0967_ (
    .A(_0321_),
    .B(_0323_),
    .Y(_0325_)
  );
  NOR _0968_ (
    .A(_0039_),
    .B(BALANCE_INICIAL[8]),
    .Y(_0326_)
  );
  NAND _0969_ (
    .A(MONTO[8]),
    .B(_0070_),
    .Y(_0327_)
  );
  NOR _0970_ (
    .A(_0040_),
    .B(BALANCE_INICIAL[9]),
    .Y(_0328_)
  );
  NAND _0971_ (
    .A(MONTO[9]),
    .B(_0071_),
    .Y(_0329_)
  );
  NOR _0972_ (
    .A(_0326_),
    .B(_0328_),
    .Y(_0330_)
  );
  NAND _0973_ (
    .A(_0327_),
    .B(_0329_),
    .Y(_0331_)
  );
  NOR _0974_ (
    .A(_0325_),
    .B(_0331_),
    .Y(_0332_)
  );
  NAND _0975_ (
    .A(_0324_),
    .B(_0330_),
    .Y(_0333_)
  );
  NOR _0976_ (
    .A(MONTO[15]),
    .B(_0077_),
    .Y(_0334_)
  );
  NAND _0977_ (
    .A(_0046_),
    .B(BALANCE_INICIAL[15]),
    .Y(_0335_)
  );
  NOR _0978_ (
    .A(MONTO[14]),
    .B(_0076_),
    .Y(_0336_)
  );
  NAND _0979_ (
    .A(_0045_),
    .B(BALANCE_INICIAL[14]),
    .Y(_0337_)
  );
  NOR _0980_ (
    .A(_0334_),
    .B(_0336_),
    .Y(_0338_)
  );
  NAND _0981_ (
    .A(_0335_),
    .B(_0337_),
    .Y(_0339_)
  );
  NOR _0982_ (
    .A(_0044_),
    .B(BALANCE_INICIAL[13]),
    .Y(_0340_)
  );
  NAND _0983_ (
    .A(MONTO[13]),
    .B(_0075_),
    .Y(_0341_)
  );
  NOR _0984_ (
    .A(_0045_),
    .B(BALANCE_INICIAL[14]),
    .Y(_0342_)
  );
  NAND _0985_ (
    .A(MONTO[14]),
    .B(_0076_),
    .Y(_0343_)
  );
  NOR _0986_ (
    .A(_0340_),
    .B(_0342_),
    .Y(_0344_)
  );
  NAND _0987_ (
    .A(_0341_),
    .B(_0343_),
    .Y(_0345_)
  );
  NOR _0988_ (
    .A(_0339_),
    .B(_0345_),
    .Y(_0346_)
  );
  NAND _0989_ (
    .A(_0338_),
    .B(_0344_),
    .Y(_0347_)
  );
  NOR _0990_ (
    .A(_0333_),
    .B(_0347_),
    .Y(_0348_)
  );
  NAND _0991_ (
    .A(_0332_),
    .B(_0346_),
    .Y(_0349_)
  );
  NOR _0992_ (
    .A(_0041_),
    .B(BALANCE_INICIAL[10]),
    .Y(_0350_)
  );
  NAND _0993_ (
    .A(MONTO[10]),
    .B(_0072_),
    .Y(_0351_)
  );
  NOR _0994_ (
    .A(_0042_),
    .B(BALANCE_INICIAL[11]),
    .Y(_0352_)
  );
  NAND _0995_ (
    .A(MONTO[11]),
    .B(_0073_),
    .Y(_0353_)
  );
  NOR _0996_ (
    .A(_0350_),
    .B(_0352_),
    .Y(_0354_)
  );
  NAND _0997_ (
    .A(_0351_),
    .B(_0353_),
    .Y(_0355_)
  );
  NOR _0998_ (
    .A(MONTO[10]),
    .B(_0072_),
    .Y(_0356_)
  );
  NAND _0999_ (
    .A(_0041_),
    .B(BALANCE_INICIAL[10]),
    .Y(_0357_)
  );
  NOR _1000_ (
    .A(MONTO[11]),
    .B(_0073_),
    .Y(_0358_)
  );
  NAND _1001_ (
    .A(_0042_),
    .B(BALANCE_INICIAL[11]),
    .Y(_0359_)
  );
  NOR _1002_ (
    .A(_0356_),
    .B(_0358_),
    .Y(_0360_)
  );
  NAND _1003_ (
    .A(_0357_),
    .B(_0359_),
    .Y(_0361_)
  );
  NOR _1004_ (
    .A(_0355_),
    .B(_0361_),
    .Y(_0362_)
  );
  NAND _1005_ (
    .A(_0354_),
    .B(_0360_),
    .Y(_0363_)
  );
  NOR _1006_ (
    .A(_0043_),
    .B(BALANCE_INICIAL[12]),
    .Y(_0364_)
  );
  NAND _1007_ (
    .A(MONTO[12]),
    .B(_0074_),
    .Y(_0365_)
  );
  NOR _1008_ (
    .A(MONTO[9]),
    .B(_0071_),
    .Y(_0366_)
  );
  NAND _1009_ (
    .A(_0040_),
    .B(BALANCE_INICIAL[9]),
    .Y(_0367_)
  );
  NOR _1010_ (
    .A(_0364_),
    .B(_0366_),
    .Y(_0368_)
  );
  NAND _1011_ (
    .A(_0365_),
    .B(_0367_),
    .Y(_0369_)
  );
  NOR _1012_ (
    .A(_0046_),
    .B(BALANCE_INICIAL[15]),
    .Y(_0370_)
  );
  NAND _1013_ (
    .A(MONTO[15]),
    .B(_0077_),
    .Y(_0371_)
  );
  NOR _1014_ (
    .A(MONTO[8]),
    .B(_0070_),
    .Y(_0372_)
  );
  NAND _1015_ (
    .A(_0039_),
    .B(BALANCE_INICIAL[8]),
    .Y(_0373_)
  );
  NOR _1016_ (
    .A(_0370_),
    .B(_0372_),
    .Y(_0374_)
  );
  NAND _1017_ (
    .A(_0371_),
    .B(_0373_),
    .Y(_0375_)
  );
  NOR _1018_ (
    .A(_0369_),
    .B(_0375_),
    .Y(_0376_)
  );
  NAND _1019_ (
    .A(_0368_),
    .B(_0374_),
    .Y(_0377_)
  );
  NOR _1020_ (
    .A(_0363_),
    .B(_0377_),
    .Y(_0378_)
  );
  NAND _1021_ (
    .A(_0362_),
    .B(_0376_),
    .Y(_0379_)
  );
  NOR _1022_ (
    .A(_0349_),
    .B(_0379_),
    .Y(_0380_)
  );
  NAND _1023_ (
    .A(_0348_),
    .B(_0378_),
    .Y(_0381_)
  );
  NOR _1024_ (
    .A(_0037_),
    .B(BALANCE_INICIAL[6]),
    .Y(_0382_)
  );
  NAND _1025_ (
    .A(MONTO[6]),
    .B(_0068_),
    .Y(_0383_)
  );
  NOR _1026_ (
    .A(_0038_),
    .B(BALANCE_INICIAL[7]),
    .Y(_0384_)
  );
  NAND _1027_ (
    .A(MONTO[7]),
    .B(_0069_),
    .Y(_0385_)
  );
  NOR _1028_ (
    .A(_0382_),
    .B(_0384_),
    .Y(_0386_)
  );
  NOR _1029_ (
    .A(MONTO[5]),
    .B(_0067_),
    .Y(_0387_)
  );
  NOR _1030_ (
    .A(MONTO[6]),
    .B(_0068_),
    .Y(_0388_)
  );
  NAND _1031_ (
    .A(_0037_),
    .B(BALANCE_INICIAL[6]),
    .Y(_0389_)
  );
  NOR _1032_ (
    .A(MONTO[7]),
    .B(_0069_),
    .Y(_0390_)
  );
  NAND _1033_ (
    .A(_0038_),
    .B(BALANCE_INICIAL[7]),
    .Y(_0391_)
  );
  NAND _1034_ (
    .A(_0389_),
    .B(_0391_),
    .Y(_0392_)
  );
  NOR _1035_ (
    .A(_0387_),
    .B(_0392_),
    .Y(_0393_)
  );
  NOR _1036_ (
    .A(_0382_),
    .B(_0390_),
    .Y(_0394_)
  );
  NOR _1037_ (
    .A(_0384_),
    .B(_0388_),
    .Y(_0395_)
  );
  NAND _1038_ (
    .A(_0394_),
    .B(_0395_),
    .Y(_0396_)
  );
  NOR _1039_ (
    .A(_0387_),
    .B(_0396_),
    .Y(_0397_)
  );
  NAND _1040_ (
    .A(_0386_),
    .B(_0393_),
    .Y(_0398_)
  );
  NOR _1041_ (
    .A(_0035_),
    .B(BALANCE_INICIAL[4]),
    .Y(_0399_)
  );
  NAND _1042_ (
    .A(MONTO[4]),
    .B(_0066_),
    .Y(_0400_)
  );
  NOR _1043_ (
    .A(_0036_),
    .B(BALANCE_INICIAL[5]),
    .Y(_0401_)
  );
  NAND _1044_ (
    .A(MONTO[5]),
    .B(_0067_),
    .Y(_0402_)
  );
  NOR _1045_ (
    .A(_0399_),
    .B(_0401_),
    .Y(_0403_)
  );
  NAND _1046_ (
    .A(_0400_),
    .B(_0402_),
    .Y(_0404_)
  );
  NOR _1047_ (
    .A(MONTO[4]),
    .B(_0066_),
    .Y(_0405_)
  );
  NOR _1048_ (
    .A(_0404_),
    .B(_0405_),
    .Y(_0406_)
  );
  NOR _1049_ (
    .A(_0387_),
    .B(_0405_),
    .Y(_0407_)
  );
  NAND _1050_ (
    .A(_0403_),
    .B(_0407_),
    .Y(_0408_)
  );
  NOR _1051_ (
    .A(_0396_),
    .B(_0408_),
    .Y(_0409_)
  );
  NAND _1052_ (
    .A(_0397_),
    .B(_0406_),
    .Y(_0410_)
  );
  NOR _1053_ (
    .A(MONTO[3]),
    .B(_0065_),
    .Y(_0411_)
  );
  NAND _1054_ (
    .A(_0034_),
    .B(BALANCE_INICIAL[3]),
    .Y(_0412_)
  );
  NOR _1055_ (
    .A(_0034_),
    .B(BALANCE_INICIAL[3]),
    .Y(_0413_)
  );
  NAND _1056_ (
    .A(MONTO[3]),
    .B(_0065_),
    .Y(_0414_)
  );
  NOR _1057_ (
    .A(_0411_),
    .B(_0413_),
    .Y(_0415_)
  );
  NAND _1058_ (
    .A(_0412_),
    .B(_0414_),
    .Y(_0416_)
  );
  NOR _1059_ (
    .A(_0033_),
    .B(BALANCE_INICIAL[2]),
    .Y(_0417_)
  );
  NAND _1060_ (
    .A(MONTO[2]),
    .B(_0064_),
    .Y(_0418_)
  );
  NOR _1061_ (
    .A(MONTO[2]),
    .B(_0064_),
    .Y(_0419_)
  );
  NAND _1062_ (
    .A(_0033_),
    .B(BALANCE_INICIAL[2]),
    .Y(_0420_)
  );
  NOR _1063_ (
    .A(_0417_),
    .B(_0419_),
    .Y(_0421_)
  );
  NAND _1064_ (
    .A(_0418_),
    .B(_0420_),
    .Y(_0422_)
  );
  NOR _1065_ (
    .A(_0416_),
    .B(_0422_),
    .Y(_0423_)
  );
  NAND _1066_ (
    .A(_0415_),
    .B(_0421_),
    .Y(_0424_)
  );
  NOR _1067_ (
    .A(_0032_),
    .B(BALANCE_INICIAL[1]),
    .Y(_0425_)
  );
  NAND _1068_ (
    .A(MONTO[1]),
    .B(_0063_),
    .Y(_0426_)
  );
  NOR _1069_ (
    .A(MONTO[0]),
    .B(_0062_),
    .Y(_0427_)
  );
  NOR _1070_ (
    .A(MONTO[1]),
    .B(_0063_),
    .Y(_0428_)
  );
  NOR _1071_ (
    .A(_0427_),
    .B(_0428_),
    .Y(_0429_)
  );
  NAND _1072_ (
    .A(_0426_),
    .B(_0429_),
    .Y(_0430_)
  );
  NOR _1073_ (
    .A(_0425_),
    .B(_0429_),
    .Y(_0431_)
  );
  NAND _1074_ (
    .A(_0426_),
    .B(_0430_),
    .Y(_0432_)
  );
  NOR _1075_ (
    .A(_0424_),
    .B(_0431_),
    .Y(_0433_)
  );
  NAND _1076_ (
    .A(_0423_),
    .B(_0432_),
    .Y(_0434_)
  );
  NOR _1077_ (
    .A(_0411_),
    .B(_0418_),
    .Y(_0435_)
  );
  NAND _1078_ (
    .A(_0412_),
    .B(_0417_),
    .Y(_0436_)
  );
  NOR _1079_ (
    .A(_0413_),
    .B(_0435_),
    .Y(_0437_)
  );
  NAND _1080_ (
    .A(_0414_),
    .B(_0436_),
    .Y(_0438_)
  );
  NOR _1081_ (
    .A(_0433_),
    .B(_0438_),
    .Y(_0439_)
  );
  NAND _1082_ (
    .A(_0434_),
    .B(_0437_),
    .Y(_0440_)
  );
  NOR _1083_ (
    .A(_0410_),
    .B(_0439_),
    .Y(_0441_)
  );
  NAND _1084_ (
    .A(_0409_),
    .B(_0440_),
    .Y(_0442_)
  );
  NOR _1085_ (
    .A(_0398_),
    .B(_0403_),
    .Y(_0443_)
  );
  NAND _1086_ (
    .A(_0397_),
    .B(_0404_),
    .Y(_0444_)
  );
  NOR _1087_ (
    .A(_0383_),
    .B(_0390_),
    .Y(_0445_)
  );
  NAND _1088_ (
    .A(_0382_),
    .B(_0391_),
    .Y(_0446_)
  );
  NOR _1089_ (
    .A(_0384_),
    .B(_0445_),
    .Y(_0447_)
  );
  NAND _1090_ (
    .A(_0385_),
    .B(_0446_),
    .Y(_0448_)
  );
  NOR _1091_ (
    .A(_0443_),
    .B(_0448_),
    .Y(_0449_)
  );
  NAND _1092_ (
    .A(_0444_),
    .B(_0447_),
    .Y(_0450_)
  );
  NOR _1093_ (
    .A(_0441_),
    .B(_0450_),
    .Y(_0451_)
  );
  NAND _1094_ (
    .A(_0442_),
    .B(_0449_),
    .Y(_0452_)
  );
  NOR _1095_ (
    .A(_0381_),
    .B(_0451_),
    .Y(_0453_)
  );
  NAND _1096_ (
    .A(_0380_),
    .B(_0452_),
    .Y(_0454_)
  );
  NOR _1097_ (
    .A(_0327_),
    .B(_0366_),
    .Y(_0455_)
  );
  NAND _1098_ (
    .A(_0326_),
    .B(_0367_),
    .Y(_0456_)
  );
  NOR _1099_ (
    .A(_0328_),
    .B(_0455_),
    .Y(_0457_)
  );
  NAND _1100_ (
    .A(_0329_),
    .B(_0456_),
    .Y(_0458_)
  );
  NOR _1101_ (
    .A(_0363_),
    .B(_0457_),
    .Y(_0459_)
  );
  NAND _1102_ (
    .A(_0362_),
    .B(_0458_),
    .Y(_0460_)
  );
  NOR _1103_ (
    .A(_0354_),
    .B(_0358_),
    .Y(_0461_)
  );
  NAND _1104_ (
    .A(_0355_),
    .B(_0359_),
    .Y(_0462_)
  );
  NOR _1105_ (
    .A(_0364_),
    .B(_0461_),
    .Y(_0463_)
  );
  NAND _1106_ (
    .A(_0365_),
    .B(_0462_),
    .Y(_0464_)
  );
  NOR _1107_ (
    .A(_0459_),
    .B(_0464_),
    .Y(_0465_)
  );
  NAND _1108_ (
    .A(_0460_),
    .B(_0463_),
    .Y(_0466_)
  );
  NOR _1109_ (
    .A(_0325_),
    .B(_0465_),
    .Y(_0467_)
  );
  NAND _1110_ (
    .A(_0324_),
    .B(_0466_),
    .Y(_0468_)
  );
  NOR _1111_ (
    .A(_0345_),
    .B(_0467_),
    .Y(_0469_)
  );
  NAND _1112_ (
    .A(_0344_),
    .B(_0468_),
    .Y(_0470_)
  );
  NOR _1113_ (
    .A(_0339_),
    .B(_0469_),
    .Y(_0471_)
  );
  NAND _1114_ (
    .A(_0338_),
    .B(_0470_),
    .Y(_0472_)
  );
  NOR _1115_ (
    .A(_0370_),
    .B(_0471_),
    .Y(_0473_)
  );
  NAND _1116_ (
    .A(_0371_),
    .B(_0472_),
    .Y(_0474_)
  );
  NOR _1117_ (
    .A(_0453_),
    .B(_0474_),
    .Y(_0475_)
  );
  NAND _1118_ (
    .A(_0454_),
    .B(_0473_),
    .Y(_0476_)
  );
  NOR _1119_ (
    .A(_0319_),
    .B(_0475_),
    .Y(_0477_)
  );
  NAND _1120_ (
    .A(_0318_),
    .B(_0476_),
    .Y(_0478_)
  );
  NOR _1121_ (
    .A(_0304_),
    .B(_0309_),
    .Y(_0479_)
  );
  NAND _1122_ (
    .A(_0293_),
    .B(_0298_),
    .Y(_0480_)
  );
  NAND _1123_ (
    .A(_0294_),
    .B(_0480_),
    .Y(_0481_)
  );
  NOR _1124_ (
    .A(_0479_),
    .B(_0481_),
    .Y(_0482_)
  );
  NOR _1125_ (
    .A(_0291_),
    .B(_0482_),
    .Y(_0483_)
  );
  NAND _1126_ (
    .A(_0285_),
    .B(_0288_),
    .Y(_0484_)
  );
  NOR _1127_ (
    .A(_0276_),
    .B(_0281_),
    .Y(_0485_)
  );
  NOR _1128_ (
    .A(_0277_),
    .B(_0485_),
    .Y(_0486_)
  );
  NAND _1129_ (
    .A(_0484_),
    .B(_0486_),
    .Y(_0487_)
  );
  NOR _1130_ (
    .A(_0483_),
    .B(_0487_),
    .Y(_0488_)
  );
  NOR _1131_ (
    .A(_0275_),
    .B(_0488_),
    .Y(_0489_)
  );
  NAND _1132_ (
    .A(_0262_),
    .B(_0265_),
    .Y(_0490_)
  );
  NOR _1133_ (
    .A(_0259_),
    .B(_0490_),
    .Y(_0491_)
  );
  NOR _1134_ (
    .A(_0255_),
    .B(_0257_),
    .Y(_0492_)
  );
  NOR _1135_ (
    .A(_0491_),
    .B(_0492_),
    .Y(_0493_)
  );
  NOR _1136_ (
    .A(_0252_),
    .B(_0493_),
    .Y(_0494_)
  );
  NOR _1137_ (
    .A(_0240_),
    .B(_0245_),
    .Y(_0495_)
  );
  NOR _1138_ (
    .A(_0225_),
    .B(_0232_),
    .Y(_0496_)
  );
  NAND _1139_ (
    .A(_0224_),
    .B(_0233_),
    .Y(_0497_)
  );
  NOR _1140_ (
    .A(_0226_),
    .B(_0496_),
    .Y(_0498_)
  );
  NAND _1141_ (
    .A(_0227_),
    .B(_0497_),
    .Y(_0499_)
  );
  NOR _1142_ (
    .A(_0494_),
    .B(_0495_),
    .Y(_0500_)
  );
  NAND _1143_ (
    .A(_0498_),
    .B(_0500_),
    .Y(_0501_)
  );
  NOR _1144_ (
    .A(_0489_),
    .B(_0499_),
    .Y(_0502_)
  );
  NOR _1145_ (
    .A(_0489_),
    .B(_0501_),
    .Y(_0503_)
  );
  NAND _1146_ (
    .A(_0500_),
    .B(_0502_),
    .Y(_0504_)
  );
  NOR _1147_ (
    .A(_0477_),
    .B(_0504_),
    .Y(_0505_)
  );
  NAND _1148_ (
    .A(_0478_),
    .B(_0503_),
    .Y(_0506_)
  );
  NAND _1149_ (
    .A(MONTO[0]),
    .B(_0062_),
    .Y(_0507_)
  );
  NOR _1150_ (
    .A(_0424_),
    .B(_0430_),
    .Y(_0508_)
  );
  NAND _1151_ (
    .A(_0507_),
    .B(_0508_),
    .Y(_0509_)
  );
  NOR _1152_ (
    .A(_0381_),
    .B(_0509_),
    .Y(_0510_)
  );
  NAND _1153_ (
    .A(_0380_),
    .B(_0409_),
    .Y(_0511_)
  );
  NOR _1154_ (
    .A(_0509_),
    .B(_0511_),
    .Y(_0512_)
  );
  NAND _1155_ (
    .A(_0409_),
    .B(_0510_),
    .Y(_0513_)
  );
  NOR _1156_ (
    .A(_0319_),
    .B(_0513_),
    .Y(_0514_)
  );
  NAND _1157_ (
    .A(_0318_),
    .B(_0512_),
    .Y(_0515_)
  );
  NOR _1158_ (
    .A(BALANCE_INICIAL[52]),
    .B(BALANCE_INICIAL[53]),
    .Y(_0516_)
  );
  NOR _1159_ (
    .A(BALANCE_INICIAL[54]),
    .B(BALANCE_INICIAL[55]),
    .Y(_0517_)
  );
  NAND _1160_ (
    .A(_0516_),
    .B(_0517_),
    .Y(_0518_)
  );
  NOR _1161_ (
    .A(BALANCE_INICIAL[48]),
    .B(BALANCE_INICIAL[49]),
    .Y(_0519_)
  );
  NOR _1162_ (
    .A(BALANCE_INICIAL[50]),
    .B(BALANCE_INICIAL[51]),
    .Y(_0520_)
  );
  NAND _1163_ (
    .A(_0519_),
    .B(_0520_),
    .Y(_0521_)
  );
  NOR _1164_ (
    .A(_0518_),
    .B(_0521_),
    .Y(_0522_)
  );
  NOR _1165_ (
    .A(BALANCE_INICIAL[60]),
    .B(BALANCE_INICIAL[61]),
    .Y(_0523_)
  );
  NOR _1166_ (
    .A(BALANCE_INICIAL[62]),
    .B(BALANCE_INICIAL[63]),
    .Y(_0524_)
  );
  NAND _1167_ (
    .A(_0523_),
    .B(_0524_),
    .Y(_0525_)
  );
  NOR _1168_ (
    .A(BALANCE_INICIAL[56]),
    .B(BALANCE_INICIAL[57]),
    .Y(_0526_)
  );
  NOR _1169_ (
    .A(BALANCE_INICIAL[58]),
    .B(BALANCE_INICIAL[59]),
    .Y(_0527_)
  );
  NAND _1170_ (
    .A(_0526_),
    .B(_0527_),
    .Y(_0528_)
  );
  NOR _1171_ (
    .A(_0525_),
    .B(_0528_),
    .Y(_0529_)
  );
  NAND _1172_ (
    .A(_0522_),
    .B(_0529_),
    .Y(_0530_)
  );
  NOR _1173_ (
    .A(BALANCE_INICIAL[36]),
    .B(BALANCE_INICIAL[37]),
    .Y(_0531_)
  );
  NOR _1174_ (
    .A(BALANCE_INICIAL[38]),
    .B(BALANCE_INICIAL[39]),
    .Y(_0532_)
  );
  NAND _1175_ (
    .A(_0531_),
    .B(_0532_),
    .Y(_0533_)
  );
  NOR _1176_ (
    .A(BALANCE_INICIAL[32]),
    .B(BALANCE_INICIAL[33]),
    .Y(_0534_)
  );
  NOR _1177_ (
    .A(BALANCE_INICIAL[34]),
    .B(BALANCE_INICIAL[35]),
    .Y(_0535_)
  );
  NAND _1178_ (
    .A(_0534_),
    .B(_0535_),
    .Y(_0536_)
  );
  NOR _1179_ (
    .A(_0533_),
    .B(_0536_),
    .Y(_0537_)
  );
  NOR _1180_ (
    .A(BALANCE_INICIAL[44]),
    .B(BALANCE_INICIAL[45]),
    .Y(_0538_)
  );
  NOR _1181_ (
    .A(BALANCE_INICIAL[46]),
    .B(BALANCE_INICIAL[47]),
    .Y(_0539_)
  );
  NAND _1182_ (
    .A(_0538_),
    .B(_0539_),
    .Y(_0540_)
  );
  NOR _1183_ (
    .A(BALANCE_INICIAL[40]),
    .B(BALANCE_INICIAL[41]),
    .Y(_0541_)
  );
  NOR _1184_ (
    .A(BALANCE_INICIAL[42]),
    .B(BALANCE_INICIAL[43]),
    .Y(_0542_)
  );
  NAND _1185_ (
    .A(_0541_),
    .B(_0542_),
    .Y(_0543_)
  );
  NOR _1186_ (
    .A(_0540_),
    .B(_0543_),
    .Y(_0544_)
  );
  NAND _1187_ (
    .A(_0537_),
    .B(_0544_),
    .Y(_0545_)
  );
  NOR _1188_ (
    .A(BALANCE_INICIAL[36]),
    .B(BALANCE_INICIAL[39]),
    .Y(_0546_)
  );
  NOR _1189_ (
    .A(BALANCE_INICIAL[33]),
    .B(BALANCE_INICIAL[34]),
    .Y(_0547_)
  );
  NAND _1190_ (
    .A(_0546_),
    .B(_0547_),
    .Y(_0548_)
  );
  NOR _1191_ (
    .A(BALANCE_INICIAL[40]),
    .B(BALANCE_INICIAL[43]),
    .Y(_0549_)
  );
  NOR _1192_ (
    .A(BALANCE_INICIAL[45]),
    .B(BALANCE_INICIAL[46]),
    .Y(_0550_)
  );
  NAND _1193_ (
    .A(_0549_),
    .B(_0550_),
    .Y(_0551_)
  );
  NOR _1194_ (
    .A(_0548_),
    .B(_0551_),
    .Y(_0552_)
  );
  NOR _1195_ (
    .A(BALANCE_INICIAL[53]),
    .B(BALANCE_INICIAL[54]),
    .Y(_0553_)
  );
  NOR _1196_ (
    .A(BALANCE_INICIAL[48]),
    .B(BALANCE_INICIAL[51]),
    .Y(_0554_)
  );
  NAND _1197_ (
    .A(_0553_),
    .B(_0554_),
    .Y(_0555_)
  );
  NOR _1198_ (
    .A(BALANCE_INICIAL[60]),
    .B(BALANCE_INICIAL[63]),
    .Y(_0556_)
  );
  NOR _1199_ (
    .A(BALANCE_INICIAL[57]),
    .B(BALANCE_INICIAL[58]),
    .Y(_0557_)
  );
  NAND _1200_ (
    .A(_0556_),
    .B(_0557_),
    .Y(_0558_)
  );
  NOR _1201_ (
    .A(_0555_),
    .B(_0558_),
    .Y(_0559_)
  );
  NOT _1202_ (
    .A(_0559_),
    .Y(_0560_)
  );
  NOR _1203_ (
    .A(BALANCE_INICIAL[52]),
    .B(BALANCE_INICIAL[55]),
    .Y(_0561_)
  );
  NOR _1204_ (
    .A(BALANCE_INICIAL[49]),
    .B(BALANCE_INICIAL[50]),
    .Y(_0562_)
  );
  NAND _1205_ (
    .A(_0561_),
    .B(_0562_),
    .Y(_0563_)
  );
  NOR _1206_ (
    .A(BALANCE_INICIAL[61]),
    .B(BALANCE_INICIAL[62]),
    .Y(_0564_)
  );
  NOR _1207_ (
    .A(BALANCE_INICIAL[56]),
    .B(BALANCE_INICIAL[59]),
    .Y(_0565_)
  );
  NAND _1208_ (
    .A(_0564_),
    .B(_0565_),
    .Y(_0566_)
  );
  NOR _1209_ (
    .A(_0563_),
    .B(_0566_),
    .Y(_0567_)
  );
  NOR _1210_ (
    .A(BALANCE_INICIAL[37]),
    .B(BALANCE_INICIAL[38]),
    .Y(_0568_)
  );
  NOR _1211_ (
    .A(BALANCE_INICIAL[32]),
    .B(BALANCE_INICIAL[35]),
    .Y(_0569_)
  );
  NAND _1212_ (
    .A(_0568_),
    .B(_0569_),
    .Y(_0570_)
  );
  NOR _1213_ (
    .A(BALANCE_INICIAL[44]),
    .B(BALANCE_INICIAL[47]),
    .Y(_0571_)
  );
  NOR _1214_ (
    .A(BALANCE_INICIAL[41]),
    .B(BALANCE_INICIAL[42]),
    .Y(_0572_)
  );
  NAND _1215_ (
    .A(_0571_),
    .B(_0572_),
    .Y(_0573_)
  );
  NOR _1216_ (
    .A(_0570_),
    .B(_0573_),
    .Y(_0574_)
  );
  NAND _1217_ (
    .A(_0567_),
    .B(_0574_),
    .Y(_0575_)
  );
  NOR _1218_ (
    .A(_0560_),
    .B(_0575_),
    .Y(_0576_)
  );
  NOR _1219_ (
    .A(_0530_),
    .B(_0545_),
    .Y(_0577_)
  );
  NAND _1220_ (
    .A(_0552_),
    .B(_0576_),
    .Y(_0578_)
  );
  NOR _1221_ (
    .A(_0514_),
    .B(_0578_),
    .Y(_0579_)
  );
  NAND _1222_ (
    .A(_0515_),
    .B(_0577_),
    .Y(_0580_)
  );
  NOR _1223_ (
    .A(_0505_),
    .B(_0580_),
    .Y(_0581_)
  );
  NAND _1224_ (
    .A(_0506_),
    .B(_0579_),
    .Y(_0582_)
  );
  NOR _1225_ (
    .A(_0028_),
    .B(_0203_),
    .Y(_0583_)
  );
  NAND _1226_ (
    .A(MONTO_STB),
    .B(_0583_),
    .Y(_0584_)
  );
  NOR _1227_ (
    .A(_0582_),
    .B(_0584_),
    .Y(FONDOS_INSUFICIENTES)
  );
  NAND _1228_ (
    .A(contador_intentos[1]),
    .B(_0215_),
    .Y(_0585_)
  );
  NOT _1229_ (
    .A(_0585_),
    .Y(ADVERTENCIA)
  );
  NOR _1230_ (
    .A(contador_intentos[1]),
    .B(_0214_),
    .Y(PIN_INCORRECTO)
  );
  NOR _1231_ (
    .A(_0061_),
    .B(_0581_),
    .Y(_0586_)
  );
  NAND _1232_ (
    .A(MONTO_STB),
    .B(_0582_),
    .Y(_0587_)
  );
  NAND _1233_ (
    .A(_0583_),
    .B(_0586_),
    .Y(_0588_)
  );
  NOT _1234_ (
    .A(_0588_),
    .Y(ENTREGAR_DINERO)
  );
  NOR _1235_ (
    .A(EstPresente[2]),
    .B(EstPresente[0]),
    .Y(_0589_)
  );
  NAND _1236_ (
    .A(EstPresente[1]),
    .B(_0589_),
    .Y(_0590_)
  );
  NOR _1237_ (
    .A(_0023_),
    .B(_0590_),
    .Y(_0591_)
  );
  NOR _1238_ (
    .A(_0201_),
    .B(_0591_),
    .Y(_0592_)
  );
  NOT _1239_ (
    .A(_0592_),
    .Y(BLOQUEO)
  );
  NOR _1240_ (
    .A(_0194_),
    .B(_0198_),
    .Y(_0593_)
  );
  NOR _1241_ (
    .A(MONTO[20]),
    .B(MONTO[21]),
    .Y(_0594_)
  );
  NOR _1242_ (
    .A(MONTO[22]),
    .B(MONTO[23]),
    .Y(_0595_)
  );
  NAND _1243_ (
    .A(_0594_),
    .B(_0595_),
    .Y(_0596_)
  );
  NOR _1244_ (
    .A(MONTO[17]),
    .B(MONTO[18]),
    .Y(_0597_)
  );
  NOR _1245_ (
    .A(MONTO[16]),
    .B(MONTO[19]),
    .Y(_0598_)
  );
  NAND _1246_ (
    .A(_0597_),
    .B(_0598_),
    .Y(_0599_)
  );
  NOR _1247_ (
    .A(_0596_),
    .B(_0599_),
    .Y(_0600_)
  );
  NOR _1248_ (
    .A(MONTO[28]),
    .B(MONTO[29]),
    .Y(_0601_)
  );
  NOR _1249_ (
    .A(MONTO[30]),
    .B(MONTO[31]),
    .Y(_0602_)
  );
  NAND _1250_ (
    .A(_0601_),
    .B(_0602_),
    .Y(_0603_)
  );
  NOR _1251_ (
    .A(MONTO[24]),
    .B(MONTO[25]),
    .Y(_0604_)
  );
  NOR _1252_ (
    .A(MONTO[26]),
    .B(MONTO[27]),
    .Y(_0605_)
  );
  NAND _1253_ (
    .A(_0604_),
    .B(_0605_),
    .Y(_0606_)
  );
  NOR _1254_ (
    .A(_0603_),
    .B(_0606_),
    .Y(_0607_)
  );
  NAND _1255_ (
    .A(_0600_),
    .B(_0607_),
    .Y(_0608_)
  );
  NOR _1256_ (
    .A(MONTO[12]),
    .B(MONTO[13]),
    .Y(_0609_)
  );
  NOR _1257_ (
    .A(MONTO[14]),
    .B(MONTO[15]),
    .Y(_0610_)
  );
  NAND _1258_ (
    .A(_0609_),
    .B(_0610_),
    .Y(_0611_)
  );
  NOR _1259_ (
    .A(MONTO[9]),
    .B(MONTO[10]),
    .Y(_0612_)
  );
  NOR _1260_ (
    .A(MONTO[8]),
    .B(MONTO[11]),
    .Y(_0613_)
  );
  NAND _1261_ (
    .A(_0612_),
    .B(_0613_),
    .Y(_0614_)
  );
  NOR _1262_ (
    .A(_0611_),
    .B(_0614_),
    .Y(_0615_)
  );
  NOR _1263_ (
    .A(MONTO[4]),
    .B(MONTO[5]),
    .Y(_0616_)
  );
  NOR _1264_ (
    .A(MONTO[6]),
    .B(MONTO[7]),
    .Y(_0617_)
  );
  NAND _1265_ (
    .A(_0616_),
    .B(_0617_),
    .Y(_0618_)
  );
  NOR _1266_ (
    .A(MONTO[0]),
    .B(MONTO[1]),
    .Y(_0619_)
  );
  NOR _1267_ (
    .A(MONTO[2]),
    .B(MONTO[3]),
    .Y(_0620_)
  );
  NAND _1268_ (
    .A(_0619_),
    .B(_0620_),
    .Y(_0621_)
  );
  NOR _1269_ (
    .A(_0618_),
    .B(_0621_),
    .Y(_0622_)
  );
  NAND _1270_ (
    .A(_0615_),
    .B(_0622_),
    .Y(_0623_)
  );
  NOR _1271_ (
    .A(_0608_),
    .B(_0623_),
    .Y(_0624_)
  );
  NOR _1272_ (
    .A(_0061_),
    .B(_0624_),
    .Y(_0625_)
  );
  NOR _1273_ (
    .A(_0030_),
    .B(_0196_),
    .Y(_0626_)
  );
  NAND _1274_ (
    .A(EstPresente[1]),
    .B(_0195_),
    .Y(_0627_)
  );
  NOR _1275_ (
    .A(_0625_),
    .B(_0627_),
    .Y(_0628_)
  );
  NAND _1276_ (
    .A(EstPresente[2]),
    .B(EstPresente[0]),
    .Y(_0629_)
  );
  NOR _1277_ (
    .A(EstPresente[1]),
    .B(_0629_),
    .Y(_0630_)
  );
  NOT _1278_ (
    .A(_0630_),
    .Y(_0631_)
  );
  NOR _1279_ (
    .A(TIPO_TRNANS),
    .B(_0631_),
    .Y(_0632_)
  );
  NOR _1280_ (
    .A(_0628_),
    .B(_0632_),
    .Y(_0633_)
  );
  NAND _1281_ (
    .A(_0218_),
    .B(_0633_),
    .Y(_0634_)
  );
  NOT _1282_ (
    .A(_0634_),
    .Y(_0635_)
  );
  NOR _1283_ (
    .A(_0205_),
    .B(_0593_),
    .Y(_0636_)
  );
  NAND _1284_ (
    .A(_0635_),
    .B(_0636_),
    .Y(_0642_[0])
  );
  NAND _1285_ (
    .A(_0592_),
    .B(_0633_),
    .Y(_0642_[1])
  );
  NAND _1286_ (
    .A(_0583_),
    .B(_0587_),
    .Y(_0637_)
  );
  NAND _1287_ (
    .A(TIPO_TRNANS),
    .B(_0630_),
    .Y(_0638_)
  );
  NOT _1288_ (
    .A(_0638_),
    .Y(_0639_)
  );
  NOR _1289_ (
    .A(_0593_),
    .B(_0639_),
    .Y(_0640_)
  );
  NAND _1290_ (
    .A(_0637_),
    .B(_0640_),
    .Y(_0642_[2])
  );
  NAND _1291_ (
    .A(_0625_),
    .B(_0626_),
    .Y(_0641_)
  );
  NAND _1292_ (
    .A(_0588_),
    .B(_0641_),
    .Y(BALANCE_ACTUALIZADO)
  );
  NOR _1293_ (
    .A(contador_intentos[1]),
    .B(_0214_),
    .Y(_0000_)
  );
  (* src = "cajero.v:44.5-161.8" *)
  always @*
    if (!_0000_) ProxEstado[0] = _0642_[0];
  (* src = "cajero.v:44.5-161.8" *)
  always @*
    if (!_0000_) ProxEstado[1] = _0642_[1];
  (* src = "cajero.v:44.5-161.8" *)
  always @*
    if (!_0000_) ProxEstado[2] = _0642_[2];
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1297_ (
    .C(clk),
    .D(_0001_),
    .Q(pin_recibido[0])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1298_ (
    .C(clk),
    .D(_0002_),
    .Q(pin_recibido[1])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1299_ (
    .C(clk),
    .D(_0003_),
    .Q(pin_recibido[2])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1300_ (
    .C(clk),
    .D(_0004_),
    .Q(pin_recibido[3])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1301_ (
    .C(clk),
    .D(_0005_),
    .Q(pin_recibido[4])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1302_ (
    .C(clk),
    .D(_0006_),
    .Q(pin_recibido[5])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1303_ (
    .C(clk),
    .D(_0007_),
    .Q(pin_recibido[6])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1304_ (
    .C(clk),
    .D(_0008_),
    .Q(pin_recibido[7])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1305_ (
    .C(clk),
    .D(_0009_),
    .Q(pin_recibido[8])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1306_ (
    .C(clk),
    .D(_0010_),
    .Q(pin_recibido[9])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1307_ (
    .C(clk),
    .D(_0011_),
    .Q(pin_recibido[10])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1308_ (
    .C(clk),
    .D(_0012_),
    .Q(pin_recibido[11])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1309_ (
    .C(clk),
    .D(_0013_),
    .Q(pin_recibido[12])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1310_ (
    .C(clk),
    .D(_0014_),
    .Q(pin_recibido[13])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1311_ (
    .C(clk),
    .D(_0015_),
    .Q(pin_recibido[14])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1312_ (
    .C(clk),
    .D(_0016_),
    .Q(pin_recibido[15])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1313_ (
    .C(clk),
    .D(_0017_),
    .Q(EstPresente[0])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1314_ (
    .C(clk),
    .D(_0018_),
    .Q(EstPresente[1])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1315_ (
    .C(clk),
    .D(_0019_),
    .Q(EstPresente[2])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1316_ (
    .C(clk),
    .D(_0020_),
    .Q(contador_intentos[0])
  );
  (* src = "cajero.v:26.5-42.8" *)
  DFF _1317_ (
    .C(clk),
    .D(_0021_),
    .Q(contador_intentos[1])
  );
endmodule
