/* Generated by Yosys 0.44+20 (git sha1 5fb3c0b1d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "control_de_acceso.v:2.1-94.10" *)
module control_acceso(llegado_vehiculo, paso_vehiculo, tercer_intento, boton_reset, clk, reset, clave_ingresada, abriendo_compuerta, cerrando_compuerta, alarm_bloqueo, alarm_pin_incorrecto);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  (* src = "control_de_acceso.v:9.12-9.26" *)
  wire [15:0] CLAVE_CORRECTA;
  (* src = "control_de_acceso.v:8.11-8.22" *)
  wire [1:0] EstPresente;
  (* src = "control_de_acceso.v:5.16-5.34" *)
  output abriendo_compuerta;
  wire abriendo_compuerta;
  (* src = "control_de_acceso.v:5.56-5.69" *)
  output alarm_bloqueo;
  wire alarm_bloqueo;
  (* src = "control_de_acceso.v:5.71-5.91" *)
  output alarm_pin_incorrecto;
  wire alarm_pin_incorrecto;
  (* src = "control_de_acceso.v:3.65-3.76" *)
  input boton_reset;
  wire boton_reset;
  (* src = "control_de_acceso.v:5.36-5.54" *)
  output cerrando_compuerta;
  wire cerrando_compuerta;
  (* src = "control_de_acceso.v:4.23-4.38" *)
  input [15:0] clave_ingresada;
  wire [15:0] clave_ingresada;
  (* src = "control_de_acceso.v:3.78-3.81" *)
  input clk;
  wire clk;
  (* src = "control_de_acceso.v:8.36-8.53" *)
  wire [1:0] contador_intentos;
  (* src = "control_de_acceso.v:3.16-3.32" *)
  input llegado_vehiculo;
  wire llegado_vehiculo;
  (* src = "control_de_acceso.v:3.34-3.47" *)
  input paso_vehiculo;
  wire paso_vehiculo;
  (* src = "control_de_acceso.v:3.83-3.88" *)
  input reset;
  wire reset;
  (* src = "control_de_acceso.v:3.49-3.63" *)
  input tercer_intento;
  wire tercer_intento;
  NOR _059_ (
    .A(EstPresente[0]),
    .B(_008_),
    .Y(_050_)
  );
  NAND _060_ (
    .A(_007_),
    .B(EstPresente[1]),
    .Y(_051_)
  );
  NAND _061_ (
    .A(_009_),
    .B(paso_vehiculo),
    .Y(_052_)
  );
  NAND _062_ (
    .A(_050_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _063_ (
    .A(contador_intentos[1]),
    .B(contador_intentos[0]),
    .Y(_054_)
  );
  NOT _064_ (
    .A(_054_),
    .Y(alarm_pin_incorrecto)
  );
  NOR _065_ (
    .A(_017_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _066_ (
    .A(_011_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _067_ (
    .A(_053_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _068_ (
    .A(abriendo_compuerta),
    .B(_057_),
    .Y(_058_)
  );
  NOR _069_ (
    .A(reset),
    .B(_058_),
    .Y(_003_)
  );
  NOR _070_ (
    .A(_051_),
    .B(_052_),
    .Y(cerrando_compuerta)
  );
  NOT _071_ (
    .A(contador_intentos[0]),
    .Y(_004_)
  );
  NOT _072_ (
    .A(reset),
    .Y(_005_)
  );
  NOT _073_ (
    .A(clave_ingresada[12]),
    .Y(_006_)
  );
  NOT _074_ (
    .A(EstPresente[0]),
    .Y(_007_)
  );
  NOT _075_ (
    .A(EstPresente[1]),
    .Y(_008_)
  );
  NOT _076_ (
    .A(llegado_vehiculo),
    .Y(_009_)
  );
  NAND _077_ (
    .A(EstPresente[0]),
    .B(EstPresente[1]),
    .Y(_010_)
  );
  NOT _078_ (
    .A(_010_),
    .Y(alarm_bloqueo)
  );
  NOR _079_ (
    .A(boton_reset),
    .B(_010_),
    .Y(_011_)
  );
  NOT _080_ (
    .A(_011_),
    .Y(_012_)
  );
  NOR _081_ (
    .A(EstPresente[1]),
    .B(_009_),
    .Y(_013_)
  );
  NOR _082_ (
    .A(EstPresente[0]),
    .B(_013_),
    .Y(_014_)
  );
  NOR _083_ (
    .A(_011_),
    .B(_014_),
    .Y(_015_)
  );
  NOR _084_ (
    .A(_004_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _085_ (
    .A(EstPresente[0]),
    .B(_008_),
    .Y(_017_)
  );
  NOT _086_ (
    .A(_017_),
    .Y(_018_)
  );
  NOR _087_ (
    .A(clave_ingresada[0]),
    .B(clave_ingresada[1]),
    .Y(_019_)
  );
  NAND _088_ (
    .A(clave_ingresada[2]),
    .B(clave_ingresada[8]),
    .Y(_020_)
  );
  NOT _089_ (
    .A(_020_),
    .Y(_021_)
  );
  NAND _090_ (
    .A(_019_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _091_ (
    .A(clave_ingresada[11]),
    .B(clave_ingresada[15]),
    .Y(_023_)
  );
  NOR _092_ (
    .A(clave_ingresada[6]),
    .B(clave_ingresada[9]),
    .Y(_024_)
  );
  NAND _093_ (
    .A(_023_),
    .B(_024_),
    .Y(_025_)
  );
  NOR _094_ (
    .A(_022_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _095_ (
    .A(_006_),
    .B(clave_ingresada[3]),
    .Y(_027_)
  );
  NAND _096_ (
    .A(clave_ingresada[4]),
    .B(clave_ingresada[7]),
    .Y(_028_)
  );
  NOT _097_ (
    .A(_028_),
    .Y(_029_)
  );
  NAND _098_ (
    .A(_027_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _099_ (
    .A(clave_ingresada[13]),
    .B(clave_ingresada[14]),
    .Y(_031_)
  );
  NOR _100_ (
    .A(clave_ingresada[5]),
    .B(clave_ingresada[10]),
    .Y(_032_)
  );
  NAND _101_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _102_ (
    .A(_030_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _103_ (
    .A(_026_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _104_ (
    .A(_018_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _105_ (
    .A(contador_intentos[1]),
    .B(_004_),
    .Y(_037_)
  );
  NOR _106_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  NOR _107_ (
    .A(_016_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _108_ (
    .A(reset),
    .B(_039_),
    .Y(_000_)
  );
  NOR _109_ (
    .A(_004_),
    .B(_036_),
    .Y(_040_)
  );
  NOR _110_ (
    .A(contador_intentos[1]),
    .B(_040_),
    .Y(_041_)
  );
  NAND _111_ (
    .A(_015_),
    .B(_036_),
    .Y(_042_)
  );
  NAND _112_ (
    .A(_005_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _113_ (
    .A(_041_),
    .B(_043_),
    .Y(_001_)
  );
  NAND _114_ (
    .A(llegado_vehiculo),
    .B(paso_vehiculo),
    .Y(_044_)
  );
  NOT _115_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR _116_ (
    .A(_013_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _117_ (
    .A(EstPresente[0]),
    .B(_046_),
    .Y(_047_)
  );
  NAND _118_ (
    .A(_012_),
    .B(_036_),
    .Y(_048_)
  );
  NOR _119_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _120_ (
    .A(reset),
    .B(_049_),
    .Y(_002_)
  );
  NOR _121_ (
    .A(_017_),
    .B(_035_),
    .Y(abriendo_compuerta)
  );
  (* src = "control_de_acceso.v:19.1-29.4" *)
  DFF _122_ (
    .C(clk),
    .D(_000_),
    .Q(contador_intentos[0])
  );
  (* src = "control_de_acceso.v:19.1-29.4" *)
  DFF _123_ (
    .C(clk),
    .D(_001_),
    .Q(contador_intentos[1])
  );
  (* src = "control_de_acceso.v:19.1-29.4" *)
  DFF _124_ (
    .C(clk),
    .D(_002_),
    .Q(EstPresente[0])
  );
  (* src = "control_de_acceso.v:19.1-29.4" *)
  DFF _125_ (
    .C(clk),
    .D(_003_),
    .Q(EstPresente[1])
  );
  assign CLAVE_CORRECTA = 16'h1194;
endmodule
