/* Generated by Yosys 0.44+20 (git sha1 5fb3c0b1d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "control_de_acceso.v:2.1-94.10" *)
module control_acceso(llegado_vehiculo, paso_vehiculo, tercer_intento, boton_reset, clk, reset, clave_ingresada, abriendo_compuerta, cerrando_compuerta, alarm_bloqueo, alarm_pin_incorrecto);
  (* src = "control_de_acceso.v:32.1-84.4" *)
  wire [1:0] _000_;
  (* src = "control_de_acceso.v:32.1-84.4" *)
  wire [1:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire [7:0] _019_;
  wire [3:0] _020_;
  wire [1:0] _021_;
  wire [1:0] _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire [1:0] _027_;
  wire [1:0] _028_;
  wire [1:0] _029_;
  wire [2:0] _030_;
  (* src = "control_de_acceso.v:89.64-89.98" *)
  wire _031_;
  (* src = "control_de_acceso.v:89.81-89.98" *)
  wire _032_;
  (* force_downto = 32'd1 *)
  (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [5:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [5:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [1:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [7:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [7:0] _038_;
  (* force_downto = 32'd1 *)
  (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [3:0] _039_;
  (* force_downto = 32'd1 *)
  (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [1:0] _040_;
  (* force_downto = 32'd1 *)
  (* src = "control_de_acceso.v:56.42-56.63|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _041_;
  (* force_downto = 32'd1 *)
  (* src = "control_de_acceso.v:56.42-56.63|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "2" *)
  wire [31:0] _042_;
  (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _043_;
  (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _044_;
  (* src = "control_de_acceso.v:9.12-9.26" *)
  wire [15:0] CLAVE_CORRECTA;
  (* src = "control_de_acceso.v:8.11-8.22" *)
  reg [1:0] EstPresente;
  (* src = "control_de_acceso.v:8.24-8.34" *)
  wire [1:0] ProxEstado;
  (* src = "control_de_acceso.v:5.16-5.34" *)
  output abriendo_compuerta;
  wire abriendo_compuerta;
  (* src = "control_de_acceso.v:5.56-5.69" *)
  output alarm_bloqueo;
  wire alarm_bloqueo;
  (* src = "control_de_acceso.v:5.71-5.91" *)
  output alarm_pin_incorrecto;
  wire alarm_pin_incorrecto;
  (* src = "control_de_acceso.v:3.65-3.76" *)
  input boton_reset;
  wire boton_reset;
  (* src = "control_de_acceso.v:5.36-5.54" *)
  output cerrando_compuerta;
  wire cerrando_compuerta;
  (* src = "control_de_acceso.v:4.23-4.38" *)
  input [15:0] clave_ingresada;
  wire [15:0] clave_ingresada;
  (* src = "control_de_acceso.v:3.78-3.81" *)
  input clk;
  wire clk;
  (* src = "control_de_acceso.v:8.36-8.53" *)
  reg [1:0] contador_intentos;
  (* src = "control_de_acceso.v:3.16-3.32" *)
  input llegado_vehiculo;
  wire llegado_vehiculo;
  (* src = "control_de_acceso.v:3.34-3.47" *)
  input paso_vehiculo;
  wire paso_vehiculo;
  (* src = "control_de_acceso.v:8.55-8.77" *)
  wire [1:0] prox_contador_intentos;
  (* src = "control_de_acceso.v:3.83-3.88" *)
  input reset;
  wire reset;
  (* src = "control_de_acceso.v:3.49-3.63" *)
  input tercer_intento;
  wire tercer_intento;
  (* src = "control_de_acceso.v:19.1-29.4" *)
  always @(posedge clk)
    if (reset) contador_intentos[0] <= 1'h0;
    else if (_006_) contador_intentos[0] <= prox_contador_intentos[0];
  (* src = "control_de_acceso.v:19.1-29.4" *)
  always @(posedge clk)
    if (reset) contador_intentos[1] <= 1'h0;
    else if (_006_) contador_intentos[1] <= prox_contador_intentos[1];
  (* src = "control_de_acceso.v:19.1-29.4" *)
  always @(posedge clk)
    if (reset) EstPresente[0] <= 1'h0;
    else EstPresente[0] <= ProxEstado[0];
  (* src = "control_de_acceso.v:19.1-29.4" *)
  always @(posedge clk)
    if (reset) EstPresente[1] <= 1'h0;
    else EstPresente[1] <= ProxEstado[1];
  assign _007_ = ~clave_ingresada[2];
  assign _008_ = ~clave_ingresada[4];
  assign _009_ = ~clave_ingresada[7];
  assign _010_ = ~clave_ingresada[8];
  assign _011_ = ~clave_ingresada[12];
  assign _012_ = ~EstPresente[0];
  assign _013_ = ~EstPresente[1];
  assign _014_ = ~contador_intentos[1];
  assign _041_[0] = ~contador_intentos[0];
  assign _019_[0] = clave_ingresada[0] |(* src = "control_de_acceso.v:88.63-88.96" *)  clave_ingresada[1];
  assign _019_[1] = _007_ |(* src = "control_de_acceso.v:88.63-88.96" *)  clave_ingresada[3];
  assign _019_[2] = _008_ |(* src = "control_de_acceso.v:88.63-88.96" *)  clave_ingresada[5];
  assign _019_[3] = clave_ingresada[6] |(* src = "control_de_acceso.v:88.63-88.96" *)  _009_;
  assign _019_[4] = _010_ |(* src = "control_de_acceso.v:88.63-88.96" *)  clave_ingresada[9];
  assign _019_[5] = clave_ingresada[10] |(* src = "control_de_acceso.v:88.63-88.96" *)  clave_ingresada[11];
  assign _019_[6] = _011_ |(* src = "control_de_acceso.v:88.63-88.96" *)  clave_ingresada[13];
  assign _019_[7] = clave_ingresada[14] |(* src = "control_de_acceso.v:88.63-88.96" *)  clave_ingresada[15];
  assign _020_[0] = _019_[0] |(* src = "control_de_acceso.v:88.63-88.96" *)  _019_[1];
  assign _020_[1] = _019_[2] |(* src = "control_de_acceso.v:88.63-88.96" *)  _019_[3];
  assign _020_[2] = _019_[4] |(* src = "control_de_acceso.v:88.63-88.96" *)  _019_[5];
  assign _020_[3] = _019_[6] |(* src = "control_de_acceso.v:88.63-88.96" *)  _019_[7];
  assign _021_[0] = _020_[0] |(* src = "control_de_acceso.v:88.63-88.96" *)  _020_[1];
  assign _021_[1] = _020_[2] |(* src = "control_de_acceso.v:88.63-88.96" *)  _020_[3];
  assign _037_[4] = _021_[0] |(* src = "control_de_acceso.v:88.63-88.96" *)  _021_[1];
  assign _018_ = _041_[0] |(* src = "control_de_acceso.v:90.29-90.51" *)  _014_;
  assign _022_[0] = _005_ &(* src = {0{1'b0}} *)  _004_;
  assign _022_[1] = _003_ &(* src = {0{1'b0}} *)  _002_;
  assign _006_ = _022_[0] &(* src = {0{1'b0}} *)  _022_[1];
  assign _015_ = _012_ |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12" *)  _013_;
  assign _023_ = _018_ |(* src = {0{1'b0}} *)  _030_[1];
  assign _004_ = _023_ |(* src = {0{1'b0}} *)  _017_;
  assign _005_ = EstPresente[0] |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12" *)  _013_;
  assign _017_ = _012_ |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12" *)  EstPresente[1];
  assign _003_ = boton_reset |(* src = {0{1'b0}} *)  _015_;
  assign _002_ = llegado_vehiculo |(* src = {0{1'b0}} *)  _016_;
  assign _024_ = _034_[1] |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _034_[3];
  assign _036_[1] = _024_ |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _034_[5];
  assign _025_ = _034_[1] |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _034_[2];
  assign _036_[0] = _025_ |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _034_[5];
  assign _026_ = alarm_bloqueo |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _035_[1];
  assign _043_ = _026_ |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _035_[2];
  assign _027_[0] = _038_[1] |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _038_[3];
  assign _040_[1] = _027_[0] |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _038_[5];
  assign _028_[0] = _038_[1] |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _038_[2];
  assign _028_[1] = _038_[4] |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _038_[6];
  assign _040_[0] = _028_[0] |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _028_[1];
  assign _029_[0] = alarm_bloqueo |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _039_[1];
  assign _029_[1] = _035_[1] |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _035_[2];
  assign _044_ = _029_[0] |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _029_[1];
  assign _016_ = EstPresente[0] |(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12" *)  EstPresente[1];
  assign _030_[1] = ~(* src = "control_de_acceso.v:88.63-88.96" *) _037_[4];
  assign alarm_pin_incorrecto = ~(* src = "control_de_acceso.v:90.29-90.51" *) _018_;
  assign alarm_bloqueo = ~(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12" *) _015_;
  assign _039_[1] = ~(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12" *) _005_;
  assign _035_[1] = ~(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12" *) _017_;
  assign _035_[2] = ~(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12" *) _016_;
  assign _037_[2] = llegado_vehiculo &(* src = "control_de_acceso.v:63.17-63.60" *)  paso_vehiculo;
  assign abriendo_compuerta = _035_[1] &(* src = "control_de_acceso.v:88.26-88.97" *)  _030_[1];
  assign _031_ = paso_vehiculo &(* src = "control_de_acceso.v:89.64-89.98" *)  _032_;
  assign cerrando_compuerta = _039_[1] &(* src = "control_de_acceso.v:89.26-89.99" *)  _031_;
  assign _033_[1] = boton_reset ? (* src = "control_de_acceso.v:76.22-76.33|control_de_acceso.v:76.18-82.16" *) 1'h0 : 1'hx;
  assign _037_[1] = ~(* src = "control_de_acceso.v:76.22-76.33|control_de_acceso.v:76.18-82.16" *) boton_reset;
  assign _001_[1] = ~(* src = "control_de_acceso.v:67.22-67.35|control_de_acceso.v:67.18-73.16" *) paso_vehiculo;
  assign _037_[3] = _037_[2] ? (* src = "control_de_acceso.v:63.17-63.60|control_de_acceso.v:63.13-73.16" *) 1'h1 : _001_[1];
  assign _000_[0] = _018_ ? (* src = "control_de_acceso.v:52.22-52.44|control_de_acceso.v:52.18-58.16" *) _041_[0] : 1'hx;
  assign _000_[1] = _018_ ? (* src = "control_de_acceso.v:52.22-52.44|control_de_acceso.v:52.18-58.16" *) _042_[1] : 1'hx;
  assign _033_[2] = _037_[4] ? (* src = "control_de_acceso.v:47.17-47.50|control_de_acceso.v:47.13-58.16" *) _000_[0] : 1'h0;
  assign _033_[3] = _037_[4] ? (* src = "control_de_acceso.v:47.17-47.50|control_de_acceso.v:47.13-58.16" *) _000_[1] : 1'h0;
  assign _037_[5] = _037_[4] ? (* src = "control_de_acceso.v:47.17-47.50|control_de_acceso.v:47.13-58.16" *) alarm_pin_incorrecto : 1'h1;
  assign _033_[5] = llegado_vehiculo ? (* src = "control_de_acceso.v:37.18-37.34|control_de_acceso.v:37.14-43.16" *) 1'h0 : 1'hx;
  assign prox_contador_intentos[0] = _043_ ? (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _036_[0] : 1'hx;
  assign prox_contador_intentos[1] = _043_ ? (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _036_[1] : 1'hx;
  assign ProxEstado[0] = _044_ ? (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _040_[0] : 1'hx;
  assign ProxEstado[1] = _044_ ? (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _040_[1] : 1'hx;
  assign _032_ = ~(* src = "control_de_acceso.v:89.81-89.98" *) llegado_vehiculo;
  assign _034_[5] = _033_[5] &(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _035_[2];
  assign _034_[2] = _033_[2] &(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _035_[1];
  assign _034_[3] = _033_[3] &(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _035_[1];
  assign _034_[1] = _033_[1] &(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  alarm_bloqueo;
  assign _038_[6] = llegado_vehiculo &(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _035_[2];
  assign _038_[4] = _037_[4] &(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _035_[1];
  assign _038_[5] = _037_[5] &(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _035_[1];
  assign _038_[2] = _037_[2] &(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _039_[1];
  assign _038_[3] = _037_[3] &(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _039_[1];
  assign _038_[1] = _037_[1] &(* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:35.5-83.12|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  alarm_bloqueo;
  assign _042_[1] = contador_intentos[1] ^(* src = "control_de_acceso.v:56.42-56.63|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  contador_intentos[0];
  assign _001_[0] = 1'h0;
  assign _027_[1] = _038_[5];
  assign { _030_[2], _030_[0] } = { _017_, _018_ };
  assign { _033_[4], _033_[0] } = { _033_[5], _033_[1] };
  assign { _034_[4], _034_[0] } = { _034_[5], _034_[1] };
  assign _035_[0] = alarm_bloqueo;
  assign { _037_[7:6], _037_[0] } = { 1'h0, llegado_vehiculo, _037_[1] };
  assign { _038_[7], _038_[0] } = { 1'h0, _038_[1] };
  assign { _039_[3:2], _039_[0] } = { _035_[2:1], alarm_bloqueo };
  assign _041_[31:1] = { 30'h00000000, contador_intentos[1] };
  assign { _042_[31:3], _042_[0] } = { 29'h00000000, _041_[0] };
  assign CLAVE_CORRECTA = 16'h1194;
endmodule
