/* Generated by Yosys 0.44+20 (git sha1 5fb3c0b1d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* src = "control_de_acceso.v:2.1-81.10" *)
module control_acceso(llegado_vehiculo, paso_vehiculo, tercer_intento, boton_reset, clk, reset, clave_ingresada, abriendo_compuerta, cerrando_compuerta, alarm_bloqueo, alarm_pin_incorrecto);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  (* force_downto = 32'd1 *)
  (* src = "control_de_acceso.v:0.0-0.0|control_de_acceso.v:31.5-70.12|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [1:0] _29_;
  (* src = "control_de_acceso.v:9.12-9.26" *)
  wire [15:0] CLAVE_CORRECTA;
  (* src = "control_de_acceso.v:8.11-8.22" *)
  reg [1:0] EstPresente;
  (* src = "control_de_acceso.v:8.24-8.34" *)
  reg [1:0] ProxEstado;
  (* src = "control_de_acceso.v:5.16-5.34" *)
  output abriendo_compuerta;
  wire abriendo_compuerta;
  (* src = "control_de_acceso.v:5.56-5.69" *)
  output alarm_bloqueo;
  wire alarm_bloqueo;
  (* src = "control_de_acceso.v:5.71-5.91" *)
  output alarm_pin_incorrecto;
  wire alarm_pin_incorrecto;
  (* src = "control_de_acceso.v:3.65-3.76" *)
  input boton_reset;
  wire boton_reset;
  (* src = "control_de_acceso.v:5.36-5.54" *)
  output cerrando_compuerta;
  wire cerrando_compuerta;
  (* src = "control_de_acceso.v:4.23-4.38" *)
  input [15:0] clave_ingresada;
  wire [15:0] clave_ingresada;
  (* src = "control_de_acceso.v:3.78-3.81" *)
  input clk;
  wire clk;
  (* src = "control_de_acceso.v:8.36-8.53" *)
  wire [1:0] contador_intentos;
  (* src = "control_de_acceso.v:3.16-3.32" *)
  input llegado_vehiculo;
  wire llegado_vehiculo;
  (* src = "control_de_acceso.v:3.34-3.47" *)
  input paso_vehiculo;
  wire paso_vehiculo;
  (* src = "control_de_acceso.v:3.83-3.88" *)
  input reset;
  wire reset;
  (* src = "control_de_acceso.v:3.49-3.63" *)
  input tercer_intento;
  wire tercer_intento;
  assign _01_ = ~(EstPresente[0] & EstPresente[1]);
  assign alarm_bloqueo = ~_01_;
  assign _02_ = EstPresente[0] & ~(EstPresente[1]);
  assign _03_ = ~(clave_ingresada[1] | clave_ingresada[0]);
  assign _04_ = clave_ingresada[3] | ~(clave_ingresada[2]);
  assign _05_ = _03_ & ~(_04_);
  assign _06_ = clave_ingresada[5] | ~(clave_ingresada[4]);
  assign _07_ = clave_ingresada[6] | ~(clave_ingresada[7]);
  assign _08_ = _07_ | _06_;
  assign _09_ = _05_ & ~(_08_);
  assign _10_ = clave_ingresada[9] | ~(clave_ingresada[8]);
  assign _11_ = clave_ingresada[11] | clave_ingresada[10];
  assign _12_ = _11_ | _10_;
  assign _13_ = clave_ingresada[13] | ~(clave_ingresada[12]);
  assign _14_ = clave_ingresada[15] | clave_ingresada[14];
  assign _15_ = _14_ | _13_;
  assign _16_ = _15_ | _12_;
  assign _17_ = _09_ & ~(_16_);
  assign abriendo_compuerta = _17_ & _02_;
  assign _18_ = EstPresente[1] & ~(EstPresente[0]);
  assign _19_ = llegado_vehiculo | ~(paso_vehiculo);
  assign cerrando_compuerta = _18_ & ~(_19_);
  assign _20_ = ~(EstPresente[0] | EstPresente[1]);
  assign _21_ = ~(_01_ | boton_reset);
  assign _22_ = ~(paso_vehiculo & llegado_vehiculo);
  assign _23_ = _18_ & ~(_22_);
  assign _24_ = _23_ | _21_;
  assign _00_ = _02_ & ~(_17_);
  assign _25_ = _00_ | _24_;
  assign _29_[0] = _20_ ? llegado_vehiculo : _25_;
  assign _26_ = paso_vehiculo & ~(llegado_vehiculo);
  assign _27_ = _18_ & ~(_26_);
  assign _28_ = _27_ | _21_;
  assign _29_[1] = EstPresente[1] ? _28_ : EstPresente[0];
  (* src = "control_de_acceso.v:30.1-71.4" *)
  always @*
    if (!_00_) ProxEstado[0] = _29_[0];
  (* src = "control_de_acceso.v:30.1-71.4" *)
  always @*
    if (!_00_) ProxEstado[1] = _29_[1];
  (* src = "control_de_acceso.v:19.1-27.4" *)
  always @(posedge clk, posedge reset)
    if (reset) EstPresente[0] <= 1'h0;
    else EstPresente[0] <= ProxEstado[0];
  (* src = "control_de_acceso.v:19.1-27.4" *)
  always @(posedge clk, posedge reset)
    if (reset) EstPresente[1] <= 1'h0;
    else EstPresente[1] <= ProxEstado[1];
  assign CLAVE_CORRECTA = 16'h1194;
  assign alarm_pin_incorrecto = 1'h0;
  assign contador_intentos = 2'h0;
endmodule
